"""自動生成されたDWHテーブルモデル."""

from __future__ import annotations

from datetime import date, time

from interactive_ehr.models._base import DwhBaseModel


class カルテ記事DR(DwhBaseModel):
    """カルテ記事DR:医師記録（1記事につき1レコード）."""

    ROW_ID: str = ""
    件数: int = 1
    シーケンスID: str = ""
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    記載時年齢: int | None = None
    記載時月齢: int | None = None
    記載時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_記載日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    入外区分: str = ""
    保険分類: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    記載日: date = date(1000, 1, 1)
    記載時刻: time | None = None
    確定日: date | None = None
    承認日: date | None = None
    記事種別コード: str = ""
    記事種別: str = ""
    記事連番: int = 0
    記事内表示連番: int | None = None
    記事データ種別コード: str = ""
    記事データ種別: str = ""
    記事: str = ""
    未整形記事の有無: str = ""
    記事_未整形_: str = ""
    プロブレム: str = ""


class カルテ記事NS(DwhBaseModel):
    """カルテ記事NS:看護記録（1記事につき1レコード）."""

    ROW_ID: str = ""
    件数: int = 1
    シーケンスID: str = ""
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    記載時年齢: int | None = None
    記載時月齢: int | None = None
    記載時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_記載日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    入外区分: str = ""
    保険分類: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    記載日: date = date(1000, 1, 1)
    記載時刻: time | None = None
    確定日: date | None = None
    承認日: date | None = None
    記事種別コード: str = ""
    記事種別: str = ""
    記事連番: int = 0
    記事内表示連番: int | None = None
    記事データ種別コード: str = ""
    記事データ種別: str = ""
    記事: str = ""
    未整形記事の有無: str = ""
    記事_未整形_: str = ""
    プロブレム: str = ""


class カルテ記事スタッフ(DwhBaseModel):
    """カルテ記事CM:その他職種（1記事につき1レコード）."""

    ROW_ID: str = ""
    件数: int = 1
    シーケンスID: str = ""
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    記載時年齢: int | None = None
    記載時月齢: int | None = None
    記載時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_記載日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    入外区分: str = ""
    保険分類: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    記載日: date = date(1000, 1, 1)
    記載時刻: time | None = None
    確定日: date | None = None
    承認日: date | None = None
    記事種別コード: str = ""
    記事種別: str = ""
    記事連番: int = 0
    記事内表示連番: int | None = None
    記事データ種別コード: str = ""
    記事データ種別: str = ""
    記事: str = ""
    未整形記事の有無: str = ""
    記事_未整形_: str = ""
    プロブレム: str = ""


class カルテ記事その他(DwhBaseModel):
    """カルテ記事その他:その他職種記録（1記事につき1レコード）."""

    ROW_ID: str = ""
    件数: int = 1
    シーケンスID: str = ""
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    記載時年齢: int | None = None
    記載時月齢: int | None = None
    記載時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_記載日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    入外区分: str = ""
    保険分類: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    記載日: date = date(1000, 1, 1)
    記載時刻: time | None = None
    確定日: date | None = None
    承認日: date | None = None
    記事種別コード: str = ""
    記事種別: str = ""
    記事連番: int = 0
    記事内表示連番: int | None = None
    記事データ種別コード: str = ""
    記事データ種別: str = ""
    記事: str = ""
    未整形記事の有無: str = ""
    記事_未整形_: str = ""
    プロブレム: str = ""


class オーダ記事(DwhBaseModel):
    """オーダ記事:オーダ時に発生した記事（1記事につき1レコード）."""

    ROW_ID: str = ""
    件数: int = 1
    シーケンスID: str = ""
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    記載時年齢: int | None = None
    記載時月齢: int | None = None
    記載時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_記載日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    キャンセル日: date | None = None
    キャンセル時刻: time | None = None
    キャンセル種別: str = ""
    キャンセル理由: str = ""
    入外区分: str = ""
    保険分類: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    記載日: date = date(1000, 1, 1)
    記載時刻: time | None = None
    確定日: date | None = None
    承認日: date | None = None
    記事種別コード: str = ""
    記事種別: str = ""
    記事連番: int = 0
    記事内表示連番: int | None = None
    記事データ種別コード: str = ""
    記事データ種別: str = ""
    記事: str = ""
    未整形記事の有無: str = ""
    記事_未整形_: str = ""
    プロブレム: str = ""


class カルテテンプレート(DwhBaseModel):
    """テンプレートを適用して記載したカルテ（テンプレート内の1項目につき1レコード）."""

    ROW_ID: str = ""
    件数: int = 1
    シーケンスID: str = ""
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    記載時年齢: int | None = None
    記載時月齢: int | None = None
    記載時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_記載日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    入外区分: str = ""
    保険分類: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    記載日: date = date(1000, 1, 1)
    記載時刻: time | None = None
    確定日: date | None = None
    テンプレートID: str = ""
    テンプレート名: str = ""
    項目SEQ: int = 0
    項目ID: str = ""
    項目名称: str = ""
    入力方法種別コード: str = ""
    表示フォーマット: str = ""
    入力値: str = ""
    表示テキスト: str = ""
    項目詳細_タイトル_: str | None = None
    項目詳細値: str | None = None
    項目詳細数値型: float | None = None
    項目詳細DATE型: date | None = None
    項目詳細TIME型: time | None = None
    画像の有無: str = ""
    リンク情報: str = ""
    電子カルテステータス: str = ""
