"""自動生成されたDWHテーブルモデル."""

from __future__ import annotations

from datetime import date, time
from decimal import Decimal
from pydantic import Field

from interactive_ehr.models._base import DwhBaseModel


class 病棟看護日誌(DwhBaseModel):
    """病棟看護日誌情報（1病棟1日誌(患者情報の集計値)につき1レコード）."""

    ROW_ID: str = ""
    件数: int = 1
    シーケンスID: str = ""
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    施設コード: str = ""
    施設名: str = ""
    検索日の定義: str = ""
    検索日_集計対象日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    オーナーの定義: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー2の定義: str = ""
    集計対象日: date = date(1000, 1, 1)
    勤務帯区分コード: str = ""
    勤務帯コード: str = ""
    病棟コード: str = ""
    病棟: str = ""
    診療科コード: str = ""
    診療科: str = ""
    管理者サイン日時1: time | None = None
    管理者サイン日時2: time | None = None
    管理者サイン日時3: time | None = None
    管理者サイン日時4: time | None = None
    管理者サイン日時5: time | None = None
    更新者ID: str = ""
    更新者名: str = ""
    空床数: int | None = None
    稼働病床数: int | None = None
    在院患者数: int | None = None
    入院患者数: int | None = None
    緊急入院患者数: int | None = None
    転入患者数: int | None = None
    退院患者数: int | None = None
    転出患者数: int | None = None
    死亡患者数: int | None = None
    外出患者数: int | None = None
    外泊患者数: int | None = None
    外出終了患者数: int | None = None
    外泊終了患者数: int | None = None
    転科患者数: int | None = None
    担送患者数: int | None = None
    護送患者数: int | None = None
    独歩患者数: int | None = None
    重症加算患者数: int | None = None
    保護室患者数: int | None = None
    新生児数: int | None = None
    新生児出生数: int | None = None
    新生児退院数: int | None = None
    A_I患者数: int | None = None
    A_II患者数: int | None = None
    A_III患者数: int | None = None
    A_IV患者数: int | None = None
    B_I患者数: int | None = None
    B_II患者数: int | None = None
    B_III患者数: int | None = None
    B_IV患者数: int | None = None
    C_I患者数: int | None = None
    C_II患者数: int | None = None
    C_III患者数: int | None = None
    C_IV患者数: int | None = None
    I度患者数: int | None = None
    II度患者数: int | None = None
    III度患者数: int | None = None
    IV度患者数: int | None = None
    V度患者数: int | None = None
    VI度患者数: int | None = None
    重症患者数: int | None = None
    要注意者患者数: int | None = None
    要観察患者数: int | None = None
    救護者患者数: int | None = None
    家族付添患者数: int | None = None
    療養環境加算: int | None = None
    療養型病床群療養環境加算: int | None = None
    重症者等療養環境特別加算: int | None = None
    HIV重症者等療養環境特別加算: int | None = None
    無菌室加算: int | None = None
    放射線治療病室管理加算: int | None = None
    予約_一般_: int | None = None
    予約_個室_: int | None = None
    予約_多床室_: int | None = None
    手術_予定_件数: int | None = None
    手術_緊急_件数: int | None = None
    検査件数: int | None = None
    透析件数: int | None = None
    分娩件数: int | None = None
    帝王切開数: int | None = None
    人工呼吸器数: int | None = None
    経管栄養数: int | None = None
    褥瘡数: int | None = None


class バイタル(DwhBaseModel):
    """バイタル情報（1測定結果ごとに1レコード）."""

    ROW_ID: str = ""
    件数: int = 1
    シーケンスID: str = ""
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    測定時年齢: int | None = None
    測定時月齢: int | None = None
    測定時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_測定日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    病室コード: str = ""
    病室: str = ""
    オーナーの定義: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー2の定義: str = ""
    測定日: date = date(1000, 1, 1)
    測定時刻: time | None = None
    測定SEQ: int = 0
    測定対象区分: str = ""
    体温: float | None = None
    脈拍: int | None = None
    心拍数: int | None = None
    呼吸数: int | None = None
    血圧_最高_: int | None = None
    血圧_最低_: int | None = None
    SPO2: float | None = None
    トレンドコメント: str = ""
    測定値1の定義: str = ""
    測定値1: float | None = None
    測定値2の定義: str = ""
    測定値2: float | None = None
    測定値3の定義: str = ""
    測定値3: float | None = None
    測定値4の定義: str = ""
    測定値4: float | None = None
    測定値5の定義: str = ""
    測定値5: float | None = None


class 経過記録(DwhBaseModel):
    """フローシート経過記録情報（観察項目の1結果ごとに1レコード）."""

    ROW_ID: str = ""
    件数: int = 1
    シーケンスID: str = ""
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    観察時年齢: int | None = None
    観察時月齢: int | None = None
    観察時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_観察日時_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    病室コード: str = ""
    病室: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    観察日: date = date(1000, 1, 1)
    観察時刻: time | None = None
    項目分類コード1: str = ""
    項目分類名1: str = ""
    項目分類名2: str = ""
    項目SEQ: int = 0
    項目コード: str = ""
    項目名: str = ""
    入力値: str = ""
    入力値_数値_: float | None = None
    表示フォーマット: str = ""
    表示テキスト: str = ""
    単位: str = ""
    コメント: str = ""


class 看護診断(DwhBaseModel):
    """看護診断情報（1診断ごとに1レコード）."""

    ROW_ID: str = ""
    件数: int = 1
    シーケンスID: str = ""
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    診断時年齢: int | None = None
    診断時月齢: int | None = None
    診断時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_診断日時_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    キャンセル日: date | None = None
    キャンセル種別: str = ""
    入外区分: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    病室コード: str = ""
    病室: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    サブオーナー2の定義: str = ""
    サブオーナー2ID: str = ""
    サブオーナー2: str = ""
    サブオーナー2職種: str = ""
    入院日: date | None = None
    入院時刻: time | None = None
    入院回数: int = 0
    初診日: date | None = None
    診断日: date | None = None
    診断時刻: time | None = None
    診断No: str = ""
    診断分類: str = ""
    診断: str = ""
    再燃の対象: str = ""
    診断解決日: date | None = None
    診断解決区分: str = ""


class 看護診断因子(DwhBaseModel):
    """看護診断因子情報（1診断関連因子ごとに1レコード）."""

    ROW_ID: str = ""
    親ROW_ID: str = ""
    件数: int = 1
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    診断時年齢: int | None = None
    診断時月齢: int | None = None
    診断時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_診断日時_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    キャンセル日: date | None = None
    キャンセル時刻: time | None = None
    キャンセル種別: str = ""
    キャンセル理由: str = ""
    入外区分: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    病室コード: str = ""
    病室: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    サブオーナー2の定義: str = ""
    サブオーナー2ID: str = ""
    サブオーナー2: str = ""
    サブオーナー2職種: str = ""
    入院日: date | None = None
    入院時刻: time | None = None
    入院回数: int = 0
    初診日: date | None = None
    診断日: date | None = None
    診断時刻: time | None = None
    診断No: str = ""
    診断分類: str = ""
    診断: str = ""
    再燃の対象: str = ""
    診断解決日: date | None = None
    診断解決区分: str = ""
    因子連番: int | None = None
    因子種別: str = ""
    因子内容: str = ""
    評価日: date | None = None
    評価状況: str = ""


class 看護診断指標(DwhBaseModel):
    """看護診断指標情報（1診断指標ごとに1レコード）."""

    ROW_ID: str = ""
    親ROW_ID: str = ""
    件数: int = 1
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    診断時年齢: int | None = None
    診断時月齢: int | None = None
    診断時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_診断日時_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    キャンセル日: date | None = None
    キャンセル時刻: time | None = None
    キャンセル種別: str = ""
    入外区分: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    病室コード: str = ""
    病室: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    サブオーナー2の定義: str = ""
    サブオーナー2ID: str = ""
    サブオーナー2: str = ""
    サブオーナー2職種: str = ""
    入院日: date | None = None
    入院時刻: time | None = None
    入院回数: int = 0
    初診日: date | None = None
    診断日: date | None = None
    診断時刻: time | None = None
    診断No: str = ""
    診断分類: str = ""
    診断: str = ""
    再燃の対象: str = ""
    診断解決日: date | None = None
    診断解決区分: str = ""
    診断指標連番: int | None = None
    診断指標種別: str = ""
    診断指標: str = ""
    評価日: date | None = None
    評価状況: str = ""


class 看護診断NOC(DwhBaseModel):
    """看護診断NOC情報(看護成果分類)（1成果指標ごとに1レコード）."""

    ROW_ID: str = ""
    親ROW_ID: str = ""
    件数: int = 1
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    診断時年齢: int | None = None
    診断時月齢: int | None = None
    診断時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_診断日時_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    キャンセル日: date | None = None
    キャンセル時刻: time | None = None
    キャンセル種別: str = ""
    入外区分: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    病室コード: str = ""
    病室: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    サブオーナー2の定義: str = ""
    サブオーナー2ID: str = ""
    サブオーナー2: str = ""
    サブオーナー2職種: str = ""
    入院日: date | None = None
    入院時刻: time | None = None
    入院回数: int = 0
    初診日: date | None = None
    診断日: date | None = None
    診断時刻: time | None = None
    診断No: str = ""
    診断分類: str = ""
    診断: str = ""
    再燃の対象: str = ""
    診断解決日: date | None = None
    診断解決区分: str = ""
    NOC連番: int | None = None
    NOC種別: str = ""
    成果指標立案日: date | None = None
    成果指標立案者ID: str = ""
    成果指標立案者: str = ""
    立案時レベル: str = ""
    立案時レベル名: str = ""
    NOC: str = ""
    達成予定日: date | None = None
    達成目標レベル: str = ""
    達成目標レベル名: str = ""
    評価日: date | None = None
    評価レベル: str = ""
    評価レベル名: str = ""
    評価: str = ""
    評価者ID: str = ""
    評価者: str = ""


class 看護診断NIC(DwhBaseModel):
    """看護診断NIC情報(看護介入分類)（1看護介入ごとに1レコード）."""

    ROW_ID: str = ""
    親ROW_ID: str = ""
    件数: int = 1
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    診断時年齢: int | None = None
    診断時月齢: int | None = None
    診断時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_診断日時_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    キャンセル日: date | None = None
    キャンセル時刻: time | None = None
    キャンセル種別: str = ""
    入外区分: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    病室コード: str = ""
    病室: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    サブオーナー2の定義: str = ""
    サブオーナー2ID: str = ""
    サブオーナー2: str = ""
    サブオーナー2職種: str = ""
    入院日: date | None = None
    入院時刻: time | None = None
    入院回数: int = 0
    初診日: date | None = None
    診断日: date | None = None
    診断時刻: time | None = None
    診断No: str = ""
    診断分類: str = ""
    診断: str = ""
    再燃の対象: str = ""
    診断解決日: date | None = None
    診断解決区分: str = ""
    NIC連番: int | None = None
    NIC種別: str = ""
    NIC: str = ""
    評価日: date | None = None
    評価: str = ""
    評価者ID: str = ""
    評価者: str = ""


class 看護必要度I(DwhBaseModel):
    """看護必要度I（1患者1日分で1レコード）."""

    ROW_ID: str = ""
    件数: int = 1
    シーケンスID: str = ""
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    症例ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    記載時年齢: int | None = None
    記載時月齢: int | None = None
    記載時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_評価日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日: date | None = None
    キャンセル時刻: time | None = None
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    病室コード: str = ""
    病室: str = ""
    病床コード: str = ""
    病床: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    評価日: date | None = None
    対象外: str = ""
    対象外理由: str = ""
    一般病棟基準対象: str = ""
    一般病棟A得点: int | None = None
    一般病棟B得点: int | None = None
    一般病棟C得点: int | None = None
    一般病棟D得点: int | None = None
    一般病棟E得点: int | None = None
    一般病棟F得点: int | None = None
    一般病棟A評価項目数: int | None = None
    一般病棟B評価項目数: int | None = None
    一般病棟C評価項目数: int | None = None
    一般病棟D評価項目数: int | None = None
    一般病棟E評価項目数: int | None = None
    一般病棟F評価項目数: int | None = None
    HCU基準対象: str = ""
    ハイケアユニットA得点: int | None = None
    ハイケアユニットB得点: int | None = None
    ハイケアユニットC得点: int | None = None
    ハイケアユニットD得点: int | None = None
    ハイケアユニットE得点: int | None = None
    ハイケアユニットF得点: int | None = None
    ハイケアユニットA評価項目数: int | None = None
    ハイケアユニットB評価項目数: int | None = None
    ハイケアユニットC評価項目数: int | None = None
    ハイケアユニットD評価項目数: int | None = None
    ハイケアユニットE評価項目数: int | None = None
    ハイケアユニットF評価項目数: int | None = None
    ICU基準対象: str = ""
    重症度A得点: int | None = None
    重症度B得点: int | None = None
    重症度C得点: int | None = None
    重症度D得点: int | None = None
    重症度E得点: int | None = None
    重症度F得点: int | None = None
    重症度A評価項目数: int | None = None
    重症度B評価項目数: int | None = None
    重症度C評価項目数: int | None = None
    重症度D評価項目数: int | None = None
    重症度E評価項目数: int | None = None
    重症度F評価項目数: int | None = None
    一般病棟_10_1_基準対象: str = ""
    一般病棟_10_1_A得点: int | None = None
    一般病棟_10_1_B得点: int | None = None
    一般病棟_10_1_C得点: int | None = None
    一般病棟_10_1_D得点: int | None = None
    一般病棟_10_1_E得点: int | None = None
    一般病棟_10_1_F得点: int | None = None
    一般病棟_10_1_A評価項目数: int | None = None
    一般病棟_10_1_B評価項目数: int | None = None
    一般病棟_10_1_C評価項目数: int | None = None
    一般病棟_10_1_D評価項目数: int | None = None
    一般病棟_10_1_E評価項目数: int | None = None
    一般病棟_10_1_F評価項目数: int | None = None
    地域包括ケア基準対象: str = ""
    地域包括ケアA得点: int | None = None
    地域包括ケアB得点: int | None = None
    地域包括ケアC得点: int | None = None
    地域包括ケアD得点: int | None = None
    地域包括ケアE得点: int | None = None
    地域包括ケアF得点: int | None = None
    地域包括ケアA評価項目数: int | None = None
    地域包括ケアB評価項目数: int | None = None
    地域包括ケアC評価項目数: int | None = None
    地域包括ケアD評価項目数: int | None = None
    地域包括ケアE評価項目数: int | None = None
    地域包括ケアF評価項目数: int | None = None
    回復期リハビリテーション基準対象: str = ""
    回復期リハビリテーションA得点: int | None = None
    回復期リハビリテーションB得点: int | None = None
    回復期リハビリテーションC得点: int | None = None
    回復期リハビリテーションD得点: int | None = None
    回復期リハビリテーションE得点: int | None = None
    回復期リハビリテーションF得点: int | None = None
    回復期リハビリテーションA評価項目数: int | None = None
    回復期リハビリテーションB評価項目数: int | None = None
    回復期リハビリテーションC評価項目数: int | None = None
    回復期リハビリテーションD評価項目数: int | None = None
    回復期リハビリテーションE評価項目数: int | None = None
    回復期リハビリテーションF評価項目数: int | None = None
    脳卒中ケアユニット基準フラグ: str = ""
    脳卒中ケアユニットA得点: int | None = None
    脳卒中ケアユニットB得点: int | None = None
    脳卒中ケアユニットC得点: int | None = None
    脳卒中ケアユニットD得点: int | None = None
    脳卒中ケアユニットE得点: int | None = None
    脳卒中ケアユニットF得点: int | None = None
    脳卒中ケアユニットA評価項目数: int | None = None
    脳卒中ケアユニットB評価項目数: int | None = None
    脳卒中ケアユニットC評価項目数: int | None = None
    脳卒中ケアユニットD評価項目数: int | None = None
    脳卒中ケアユニットE評価項目数: int | None = None
    脳卒中ケアユニットF評価項目数: int | None = None
    新一般病棟基準フラグ: str = ""
    新一般病棟A得点: int | None = None
    新一般病棟B得点: int | None = None
    新一般病棟C得点: int | None = None
    新一般病棟D得点: int | None = None
    新一般病棟E得点: int | None = None
    新一般病棟F得点: int | None = None
    新一般病棟A評価項目数: int | None = None
    新一般病棟B評価項目数: int | None = None
    新一般病棟C評価項目数: int | None = None
    新一般病棟D評価項目数: int | None = None
    新一般病棟E評価項目数: int | None = None
    新一般病棟F評価項目数: int | None = None
    地域包括医療基準フラグ: str = ""
    地域包括医療A得点: int | None = None
    地域包括医療B得点: int | None = None
    地域包括医療C得点: int | None = None
    地域包括医療D得点: int | None = None
    地域包括医療E得点: int | None = None
    地域包括医療F得点: int | None = None
    地域包括医療A評価項目数: int | None = None
    地域包括医療B評価項目数: int | None = None
    地域包括医療C評価項目数: int | None = None
    地域包括医療D評価項目数: int | None = None
    地域包括医療E評価項目数: int | None = None
    地域包括医療F評価項目数: int | None = None


class 看護必要度II(DwhBaseModel):
    """看護必要度II（1患者1日分で1レコード）."""

    ROW_ID: str = ""
    件数: int = 1
    シーケンスID: str = ""
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    症例ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    記載時年齢: int | None = None
    記載時月齢: int | None = None
    記載時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_評価日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    病室コード: str = ""
    病室: str = ""
    病床コード: str = ""
    病床: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    評価日: date | None = None
    一般病棟対象外: str = ""
    一般病棟基準対象: str = ""
    一般病棟A得点: int | None = None
    一般病棟B得点: int | None = None
    一般病棟C得点: int | None = None
    一般病棟D得点: int | None = None
    一般病棟E得点: int | None = None
    一般病棟F得点: int | None = None
    一般病棟A評価項目数: int | None = None
    一般病棟B評価項目数: int | None = None
    一般病棟C評価項目数: int | None = None
    一般病棟D評価項目数: int | None = None
    一般病棟E評価項目数: int | None = None
    一般病棟F評価項目数: int | None = None
    ハイケアユニット対象外: str = ""
    HCU基準対象: str = ""
    ハイケアユニットA得点: int | None = None
    ハイケアユニットB得点: int | None = None
    ハイケアユニットC得点: int | None = None
    ハイケアユニットD得点: int | None = None
    ハイケアユニットE得点: int | None = None
    ハイケアユニットF得点: int | None = None
    ハイケアユニットA評価項目数: int | None = None
    ハイケアユニットB評価項目数: int | None = None
    ハイケアユニットC評価項目数: int | None = None
    ハイケアユニットD評価項目数: int | None = None
    ハイケアユニットE評価項目数: int | None = None
    ハイケアユニットF評価項目数: int | None = None
    ICU対象外: str = ""
    ICU基準対象: str = ""
    重症度A得点: int | None = None
    重症度B得点: int | None = None
    重症度C得点: int | None = None
    重症度D得点: int | None = None
    重症度E得点: int | None = None
    重症度F得点: int | None = None
    重症度A評価項目数: int | None = None
    重症度B評価項目数: int | None = None
    重症度C評価項目数: int | None = None
    重症度D評価項目数: int | None = None
    重症度E評価項目数: int | None = None
    重症度F評価項目数: int | None = None
    地域包括ケア対象外: str = ""
    地域包括ケア基準対象: str = ""
    地域包括ケアA得点: int | None = None
    地域包括ケアB得点: int | None = None
    地域包括ケアC得点: int | None = None
    地域包括ケアD得点: int | None = None
    地域包括ケアE得点: int | None = None
    地域包括ケアF得点: int | None = None
    地域包括ケアA評価項目数: int | None = None
    地域包括ケアB評価項目数: int | None = None
    地域包括ケアC評価項目数: int | None = None
    地域包括ケアD評価項目数: int | None = None
    地域包括ケアE評価項目数: int | None = None
    地域包括ケアF評価項目数: int | None = None
    脳卒中ケアユニット対象外: str = ""
    脳卒中ケアユニット基準フラグ: str = ""
    脳卒中ケアユニットA得点: int | None = None
    脳卒中ケアユニットB得点: int | None = None
    脳卒中ケアユニットC得点: int | None = None
    脳卒中ケアユニットD得点: int | None = None
    脳卒中ケアユニットE得点: int | None = None
    脳卒中ケアユニットF得点: int | None = None
    脳卒中ケアユニットA評価項目数: int | None = None
    脳卒中ケアユニットB評価項目数: int | None = None
    脳卒中ケアユニットC評価項目数: int | None = None
    脳卒中ケアユニットD評価項目数: int | None = None
    脳卒中ケアユニットE評価項目数: int | None = None
    脳卒中ケアユニットF評価項目数: int | None = None
    新一般病棟対象外: str = ""
    新一般病棟基準フラグ: str = ""
    新一般病棟A得点: int | None = None
    新一般病棟B得点: int | None = None
    新一般病棟C得点: int | None = None
    新一般病棟D得点: int | None = None
    新一般病棟E得点: int | None = None
    新一般病棟F得点: int | None = None
    新一般病棟A評価項目数: int | None = None
    新一般病棟B評価項目数: int | None = None
    新一般病棟C評価項目数: int | None = None
    新一般病棟D評価項目数: int | None = None
    新一般病棟E評価項目数: int | None = None
    新一般病棟F評価項目数: int | None = None
    地域包括医療対象外: str = ""
    地域包括医療基準フラグ: str = ""
    地域包括医療A得点: int | None = None
    地域包括医療B得点: int | None = None
    地域包括医療C得点: int | None = None
    地域包括医療D得点: int | None = None
    地域包括医療E得点: int | None = None
    地域包括医療F得点: int | None = None
    地域包括医療A評価項目数: int | None = None
    地域包括医療B評価項目数: int | None = None
    地域包括医療C評価項目数: int | None = None
    地域包括医療D評価項目数: int | None = None
    地域包括医療E評価項目数: int | None = None
    地域包括医療F評価項目数: int | None = None


class 看護DB_一般(DwhBaseModel):
    """看護DB・一般(最新の看護データベースを日次で取込)（1患者1レコード）."""

    ROW_ID: str = ""
    件数: int = 1
    シーケンスID: str = ""
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: Decimal = Decimal("0")
    キー8: Decimal = Decimal("0")
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: Decimal = Decimal("0")
    記載時年齢: int | None = None
    記載時月齢: int | None = None
    記載時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_確定日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    サマリー種別: str = ""
    アセスメント種別: str = ""
    確定日: date | None = None
    入院日: date | None = None
    入院時刻: time | None = None
    退院日: date | None = None
    確定時年齢: int | None = None
    診断日: date | None = None
    身長: Decimal | None = None
    身長測定日: date | None = None
    体重: Decimal | None = None
    体重測定日: date | None = None
    在胎_週_: int | None = None
    在胎_日_: int | None = None
    子数: int | None = None
    胎児数: int | None = None
    出生施設区分: str = ""
    出生院: str = ""


class 看護DB_ヘルスプロモーション(DwhBaseModel):
    """看護DB・ヘルスプロモーション(最新の看護データベースを日次で取込)（1患者1レコード）."""

    ROW_ID: str = ""
    親ROW_ID: str = ""
    件数: int = 1
    トランザクション名: str = ""
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: Decimal = Decimal("0")
    記載時年齢: int | None = None
    記載時月齢: int | None = None
    記載時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_確定日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    サマリー種別: str = ""
    アセスメント種別: str = ""
    確定日: date | None = None
    確定時刻: time | None = None
    入院までの経過: str = ""
    入院に対する両親の思い: str = ""
    分娩予定日: date | None = None
    IC日: date | None = None
    IC本人病名説明の有無: str = ""
    IC本人検査結果説明の有無: str = ""
    IC本人治療方針説明の有無: str = ""
    IC本人予後説明の有無: str = ""
    IC本人反応: str = ""
    ICコメント_本人_: str = ""
    IC説明: str = ""
    ICその他説明者内容: str = ""
    IC日_代表者_: date | None = None
    IC家族病名説明の有無: str = ""
    IC家族症状説明の有無: str = ""
    IC家族検査結果説明の有無: str = ""
    IC家族治療方針説明の有無: str = ""
    IC家族予後の有無: str = ""
    ICコメント_家族_: str = ""
    食事療法の有無: str = ""
    食事療法_実施率: int | None = None
    食事療法コメント: str = ""
    運動の有無: str = ""
    運動に対するコメント: str = ""
    健康上の注意点の有無: str = ""
    健康上の注意点コメント: str = ""
    食事で気をつけていること_味付け: str = ""
    食事で気をつけていること_規則性: str = ""
    喫煙本数: int | None = None
    喫煙開始年齢: int | None = None
    喫煙中止年齢: int | None = None
    飲酒回数_1: int | None = Field(None, alias="飲酒回数")
    飲酒量: int | None = None
    飲酒開始年齢: int | None = None
    飲酒中止年齢: int | None = None
    飲酒歴_年数_: int | None = None
    陣痛発来日: date | None = None
    陣痛発来時刻: time | None = None
    破水状態: str = ""
    破水開始日: date | None = None
    破水時刻: time | None = None
    羊水混濁の有無: str = ""
    妊娠中合併症の有無: str = ""
    妊娠合併症_中毒症_の有無: str = ""
    妊娠合併症_尿蛋白_の有無: str = ""
    尿糖の有無: str = ""
    切迫流早産の有無: str = ""
    貧血の有無: str = ""
    その他合併症内容: str = ""
    妊娠中毒症_最高血圧_: str = ""
    妊娠中毒症_最低血圧_: str = ""
    妊娠中毒症_浮腫_の有無: str = ""
    受け止め方_妊娠について: str = ""
    受け止め方_分娩について: str = ""
    妊娠中喫煙状況: str = ""
    妊娠中喫煙本数: int | None = None
    母親喫煙開始年齢: int | None = None
    母親喫煙中止年齢: int | None = None
    飲酒回数_2: int | None = Field(None, alias="飲酒回数")
    妊娠中飲酒量: int | None = None
    流行疾患の有無: str = ""
    流行疾患: str = ""
    ツ反の有無: str = ""
    出生時体重: int | None = None
    出生時身長: Decimal | None = None
    出生時頭囲: Decimal | None = None
    出生時胸囲: Decimal | None = None
    アプガースコア_1分_: int | None = None
    アプガースコア_5分_: int | None = None
    蘇生の有無: str = ""
    蘇生法内容: str = ""
    外表奇形の有無: str = ""
    外表奇形内容: str = ""
    清潔方法: str = ""
    入浴_回数_: int | None = None
    入浴単位: str = ""
    洗髪_回数_: int | None = None


class 看護DB_栄養(DwhBaseModel):
    """看護DB・栄養(最新の看護データベースを日次で取込)（1患者1レコード）."""

    ROW_ID: str = ""
    親ROW_ID: str = ""
    件数: int = 1
    トランザクション名: str = ""
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: Decimal = Decimal("0")
    記載時年齢: int | None = None
    記載時月齢: int | None = None
    記載時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_確定日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    サマリー種別: str = ""
    アセスメント種別: str = ""
    確定日: date | None = None
    確定時刻: time | None = None
    体重変動の有無: str = ""
    変動量: int | None = None
    変動量単位: str = ""
    変動開始期間: date | None = None
    変動終了期間: date | None = None
    体重変動内容: str = ""
    体温: Decimal | None = None
    保育環境: str = ""
    保育器収容日数: int | None = None
    保育温度: Decimal | None = None
    保育湿度: Decimal | None = None
    皮膚の状態: str = ""
    食事摂取方法: str = ""
    食事摂取方法コメント: str = ""
    食事の回数: int | None = None
    食欲の有無: str = ""
    食欲コメント: str = ""
    食事摂取の変化: str = ""
    食事摂取変化内容: str = ""
    ミルク区分: str = ""
    ミルク量_1回量_: int | None = None
    ミルク回数: int | None = None
    母乳対象: str = ""
    離乳食対象: str = ""
    普通食対象: str = ""
    離乳食開始時期: int | None = None
    哺乳開始日: date | None = None
    離乳食回数: int | None = None
    哺乳力: str = ""
    食事制限の有無: str = ""
    食事制限内容: str = ""
    摂取状況: str = ""
    摂取状況コメント: str = ""
    嗜好品の有無: str = ""
    嗜好品コメント: str = ""
    食事_ミルク要望の有無: str = ""
    食事_ミルク要望内容: str = ""
    偏食の有無: str = ""
    偏食内容: str = ""
    悪心の有無: str = ""
    嘔吐の有無: str = ""
    嘔吐_回数_: int | None = None
    食に対する影響: str = ""
    間食回数: int | None = None
    義歯の有無: str = ""
    歯の状態内容: str = ""


class 看護DB_排泄(DwhBaseModel):
    """看護DB・排泄(最新の看護データベースを日次で取込)（1患者1レコード）."""

    ROW_ID: str = ""
    親ROW_ID: str = ""
    件数: int = 1
    トランザクション名: str = ""
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: Decimal = Decimal("0")
    記載時年齢: int | None = None
    記載時月齢: int | None = None
    記載時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_確定日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    サマリー種別: str = ""
    アセスメント種別: str = ""
    確定日: date | None = None
    確定時刻: time | None = None
    排便回数_回_: int | None = None
    排便回数_日_: int | None = None
    排便_性状_: str = ""
    排便_色_: str = ""
    最終排便日: date | None = None
    最終排便時刻: time | None = None
    最終排便_性状_: str = ""
    最終排便_色_: str = ""
    排便時の状態: str = ""
    排便コメント: str = ""
    便通のための対処の有無: str = ""
    排便のコミュニケーション: str = ""
    排便のコミュニケーション_言葉_: str = ""
    排便のコミュニケーション_しぐさ_: str = ""
    ストーマの有無: str = ""
    便失禁の有無: str = ""
    排尿回数_回_日_: int | None = None
    夜尿_回数_: int | None = None
    排尿_性状_: str = ""
    第一排尿の有無: str = ""
    最終排尿日: date | None = None
    最終排尿時刻: time | None = None
    尿失禁の有無の有無: str = ""
    排尿に伴う症状: str = ""
    夜尿の有無: str = ""
    夜尿内容: str = ""
    夜尿誘導要_不要: str = ""
    トイレットトレーニング: str = ""
    排尿のコミュニケーション: str = ""
    排尿のコミュニケーション_言葉_: str = ""
    排尿のコミュニケーション_しぐさ_: str = ""
    尿路変更の有無: str = ""
    排尿の方法_その他_: str = ""
    皮膚異常の有無: str = ""
    皮膚異常コメント: str = ""


class 看護DB_活動休息(DwhBaseModel):
    """看護DB・活動休息(最新の看護データベースを日次で取込)（1患者1レコード）."""

    ROW_ID: str = ""
    親ROW_ID: str = ""
    件数: int = 1
    トランザクション名: str = ""
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: Decimal = Decimal("0")
    記載時年齢: int | None = None
    記載時月齢: int | None = None
    記載時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_確定日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    アセスメント種別: str = ""
    サマリー種別: str = ""
    確定日: date | None = None
    確定時刻: time | None = None
    痙攣_生後日数_: int | None = None
    筋緊張状態: str = ""
    筋緊張状態コメント: str = ""
    筋緊張左右差の有無: str = ""
    活動性: str = ""
    活動性詳細: str = ""
    啼泣: str = ""
    好きな遊び_テレビ: str = ""
    習い事の有無: str = ""
    習い事内容: str = ""
    食事レベル: str = ""
    食事方法: str = ""
    食事コメント: str = ""
    更衣_整容レベル: str = ""
    更衣_整容方法: str = ""
    更衣_整容コメント: str = ""
    排泄レベル: str = ""
    排泄方法: str = ""
    排泄コメント: str = ""
    移動レベル: str = ""
    移動方法: str = ""
    移動コメント: str = ""
    寝返りレベル: str = ""
    寝返りコメント: str = ""
    自助具内容: str = ""
    利手_右_左_: str = ""
    睡眠時間_昼_: int | None = None
    睡眠時間_夜_: int | None = None
    午睡_開始時刻_: int | None = None
    午睡_終了時刻_: int | None = None
    就寝時間: str = ""
    起床時間: str = ""
    熟睡感の有無: str = ""
    入眠困難の有無: str = ""
    睡眠持続困難の有無: str = ""
    不眠訴え内容: str = ""
    睡眠のための習慣コメント: str = ""
    睡眠薬の使用の有無: str = ""
    睡眠薬使用コメント: str = ""
    大泉門の状態: str = ""
    血圧_最高_: int | None = None
    血圧_最低_: int | None = None
    脈拍数: int | None = None
    動悸の有無: str = ""
    動悸コメント: str = ""
    冷汗の有無: str = ""
    チアノーゼの有無: str = ""
    チアノーゼ状態: str = ""
    チアノーゼコメント: str = ""
    ペースメーカーの設定: str = ""
    倦怠感の有無: str = ""
    浮腫_循環_の有無: str = ""
    浮腫_循環_の内容: str = ""
    呼吸数: int | None = None
    呼吸音: str = ""
    呼吸困難の有無: str = ""
    呼吸困難内容: str = ""
    鼻翼呼吸の有無: str = ""
    呻吟の有無: str = ""
    陥没呼吸の有無: str = ""
    咳嗽の有無: str = ""
    呼吸障害の有無: str = ""
    酸素療法_器具使用の有無: str = ""
    酸素吸入の有無: str = ""
    吸引器の有無: str = ""
    人工呼吸器の有無: str = ""
    気管カニューレの有無: str = ""
    酸素使用時間: int | None = None


class 看護DB_知覚認知(DwhBaseModel):
    """看護DB・知覚認知(最新の看護データベースを日次で取込)（1患者1レコード）."""

    ROW_ID: str = ""
    親ROW_ID: str = ""
    件数: int = 1
    トランザクション名: str = ""
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: Decimal = Decimal("0")
    記載時年齢: int | None = None
    記載時月齢: int | None = None
    記載時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_確定日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    サマリー種別: str = ""
    アセスメント種別: str = ""
    確定日: date | None = None
    確定時刻: time | None = None
    見当識_人物_の有無: str = ""
    見当識_場所_の有無: str = ""
    見当識_時間_の有無: str = ""
    見当識_環境_の有無: str = ""
    幻覚障害の有無: str = ""
    幻覚障害コメント: str = ""
    行動障害の有無: str = ""
    行動障害コメント: str = ""
    瞳孔障害の有無: str = ""
    瞳孔異常_不同_の有無: str = ""
    瞳孔異常_散大_の有無: str = ""
    瞳孔異常_縮小_の有無: str = ""
    対光反射障害の有無: str = ""
    瞳孔大きさ_左_: int | None = None
    瞳孔大きさ_右_: int | None = None
    対光反射障害コメント: str = ""
    吸啜反射の有無: str = ""
    開口反射障害コメント: str = ""
    嚥下反射障害の有無: str = ""
    嚥下反射障害コメント: str = ""
    四肢運動障害コメント: str = ""
    視覚障害コメント: str = ""
    聴覚障害コメント: str = ""
    補聴器使用の有無: str = ""
    嗅覚障害の有無: str = ""
    嗅覚障害コメント: str = ""
    味覚障害の有無: str = ""
    味覚障害コメント: str = ""
    触覚障害の有無: str = ""
    触覚障害コメント: str = ""
    しびれ障害の有無: str = ""
    しびれ障害コメント: str = ""
    麻痺の有無: str = ""
    麻痺コメント: str = ""
    疼痛コメント: str = ""
    記憶力障害の有無: str = ""


class 看護DB_自己知覚(DwhBaseModel):
    """看護DB・自己知覚(最新の看護データベースを日次で取込)（1患者1レコード）."""

    ROW_ID: str = ""
    親ROW_ID: str = ""
    件数: int = 1
    トランザクション名: str = ""
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: Decimal = Decimal("0")
    記載時年齢: int | None = None
    記載時月齢: int | None = None
    記載時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_確定日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    サマリー種別: str = ""
    アセスメント種別: str = ""
    確定日: date | None = None
    確定時刻: time | None = None
    自分の性格_本人_: str = ""
    母の性格_新生児_保護者の性格_小児_: str = ""
    自分の長所: str = ""
    自分の短所: str = ""
    病気の受け止め_本人_: str = ""
    病気の受け止め_親_: str = ""
    ボディイメージ変化内容: str = ""
    気がかりなこと_本人_: str = ""
    気がかりなこと_親_: str = ""
    過去の喪失や変化の有無: str = ""
    過去の喪失や変化内容: str = ""


class 看護DB_役割関係(DwhBaseModel):
    """看護DB・役割関係(最新の看護データベースを日次で取込)（1患者1レコード）."""

    ROW_ID: str = ""
    親ROW_ID: str = ""
    件数: int = 1
    トランザクション名: str = ""
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: Decimal = Decimal("0")
    記載時年齢: int | None = None
    記載時月齢: int | None = None
    記載時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_確定日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    サマリー種別: str = ""
    アセスメント種別: str = ""
    確定日: date | None = None
    家庭での役割: str = ""
    家庭での役割_その他_: str = ""
    職業の有無: str = ""
    通院時間_分_: Decimal | None = None
    交通機関コード: str = ""
    交通機関コメント: str = ""
    主な保育者コード: str = ""
    主な保育者内容: str = ""
    就学状況: str = ""
    就学状況_学年_: str = ""
    家庭内での問題の有無: str = ""
    家庭内での問題内容: str = ""
    学校での問題の有無: str = ""
    学校での問題内容: str = ""
    友人との問題の有無: str = ""
    友人との問題内容: str = ""
    育児に対しての問題の有無: str = ""
    育児に対しての問題内容: str = ""
    母親学級の受講の有無: str = ""
    訪問回数: int | None = None
    身体障害者手帳_級_: str = ""
    精神障害者保険福祉手帳の有無: str = ""
    生活保護の有無: str = ""
    デイサービス_回数_: int | None = None
    ショートステイ_回数_: int | None = None
    訪問看護_回数_: int | None = None


class 看護DB_セクシャリティ(DwhBaseModel):
    """看護DB・セクシャリティ(最新の看護データベースを日次で取込)（1患者1レコード）."""

    ROW_ID: str = ""
    親ROW_ID: str = ""
    件数: int = 1
    トランザクション名: str = ""
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: Decimal = Decimal("0")
    記載時年齢: int | None = None
    記載時月齢: int | None = None
    記載時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_確定日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    サマリー種別: str = ""
    アセスメント種別: str = ""
    確定日: date | None = None
    確定時刻: time | None = None
    初経年齢: int | None = None
    月経周期: int | None = None
    月経持続日数: int | None = None
    閉経年齢: int | None = None
    更年期障害の有無_女性_: str = ""
    更年期障害コメント_女性_: str = ""


class 看護DB_コーピング(DwhBaseModel):
    """看護DB・コーピング(最新の看護データベースを日次で取込)（1患者1レコード）."""

    ROW_ID: str = ""
    親ROW_ID: str = ""
    件数: int = 1
    トランザクション名: str = ""
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: Decimal = Decimal("0")
    記載時年齢: int | None = None
    記載時月齢: int | None = None
    記載時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_確定日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    サマリー種別: str = ""
    アセスメント種別: str = ""
    確定日: date | None = None
    確定時刻: time | None = None
    ストレスに対するコーピング_新生児の場合は母親_: str = ""


class 看護DB_生活原理(DwhBaseModel):
    """看護DB・生活原理(最新の看護データベースを日次で取込)（1患者1レコード）."""

    ROW_ID: str = ""
    親ROW_ID: str = ""
    件数: int = 1
    トランザクション名: str = ""
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: Decimal = Decimal("0")
    記載時年齢: int | None = None
    記載時月齢: int | None = None
    記載時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_確定日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    サマリー種別: str = ""
    アセスメント種別: str = ""
    確定日: date | None = None
    確定時刻: time | None = None
    宗教的な配慮の必要性有無: str = ""
    宗教に関する配慮の必要性_保護者の言葉: str = ""
    趣味_特技コメント: str = ""
    人生において重要と考えていること: str = ""


class 看護DB_安全防御(DwhBaseModel):
    """看護DB・安全防御(最新の看護データベースを日次で取込)（1患者1レコード）."""

    ROW_ID: str = ""
    親ROW_ID: str = ""
    件数: int = 1
    トランザクション名: str = ""
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: Decimal = Decimal("0")
    記載時年齢: int | None = None
    記載時月齢: int | None = None
    記載時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_確定日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    サマリー種別: str = ""
    アセスメント種別: str = ""
    確定日: date | None = None
    確定時刻: time | None = None
    自傷他害行為の既往コメント: str = ""
    創傷_皮膚の問題内容_1: str = Field("", alias="創傷・皮膚の問題内容")
    転倒_転落アセススコア: str = ""
    低体温対象: str = ""
    末梢の冷感の有無: str = ""
    ブレーデンスケール_合計点数_: int | None = None
    創傷_皮膚の問題の有無: str = ""
    創傷_皮膚の問題内容_2: str = Field("", alias="創傷・皮膚の問題内容")


class 看護DB_安楽(DwhBaseModel):
    """看護DB・安楽(最新の看護データベースを日次で取込)（1患者1レコード）."""

    ROW_ID: str = ""
    親ROW_ID: str = ""
    件数: int = 1
    トランザクション名: str = ""
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: Decimal = Decimal("0")
    記載時年齢: int | None = None
    記載時月齢: int | None = None
    記載時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_確定日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    サマリー種別: str = ""
    アセスメント種別: str = ""
    確定日: date | None = None
    確定時刻: time | None = None
    父親面会頻度: int | None = None
    母親面会頻度: int | None = None
    主に面会する人_面会頻度: int | None = None
    疼痛の有無: str = ""
    疼痛_部位: str = ""
    掻痒の有無: str = ""
    掻痒感部位: str = ""
    嘔気_嘔吐の有無: str = ""
    身体的苦痛倦怠感の有無: str = ""


class 看護DB_成長発達(DwhBaseModel):
    """看護DB・成長発達(最新の看護データベースを日次で取込)（1患者1レコード）."""

    ROW_ID: str = ""
    親ROW_ID: str = ""
    件数: int = 1
    トランザクション名: str = ""
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: Decimal = Decimal("0")
    記載時年齢: int | None = None
    記載時月齢: int | None = None
    記載時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_確定日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    サマリー種別: str = ""
    アセスメント種別: str = ""
    確定日: date | None = None
    確定時刻: time | None = None
    発育_頚定____: int | None = None
    発育_ひとりだち_: int | None = None
    発育_ひとりあるき_: int | None = None
    週数相当の発達状態_吸啜反射の有無: str = ""
    週数相当の発達状態_嚥下反射の有無: str = ""
    修正週数_週_: int | None = None
    修正週数_日_: int | None = None
    情報提供者1続柄: str = ""
    情報提供者1: str = ""
    記録者1: str = ""
    情報収集日付1: date | None = None
    情報提供者2続柄: str = ""
    情報提供者2: str = ""
    記録者2: str = ""
    情報収集日付2: date | None = None
    情報提供者3続柄: str = ""
    情報提供者3: str = ""
    記録者3: str = ""
    情報収集日付3: date | None = None
    情報提供者4続柄: str = ""
    情報提供者4: str = ""
    記録者4: str = ""
    情報収集日付4: date | None = None
    情報提供者5続柄: str = ""
    情報提供者5: str = ""
    記録者5: str = ""
    情報収集日付5: date | None = None


class 看護DB_項目リスト(DwhBaseModel):
    """看護DB・項目リスト(最新の看護データベースを日次で取込)（1患者1確定1項目につき1レコード）."""

    ROW_ID: str = ""
