"""自動生成されたDWHテーブルモデル."""

from __future__ import annotations

from datetime import date, time

from interactive_ehr.models._base import DwhBaseModel


class 検体検査(DwhBaseModel):
    """一般検体検査依頼（1検査依頼につき1レコード）."""

    ROW_ID: str = ""
    件数: int = 1
    シーケンスID: str = ""
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    採取時年齢: int | None = None
    採取時月齢: int | None = None
    採取時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_採取日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    キャンセル日: date | None = None
    キャンセル理由: str = ""
    部門発生区分: str = ""
    入外区分: str = ""
    保険分類: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    部門連係ID: str = ""
    検体採取日: date | None = None
    検体採取時刻: time | None = None
    検体提出日: date | None = None
    検体提出時刻: time | None = None
    検査材料コード: str = ""
    検査材料: str = ""
    検査目的: str = ""
    検査内容: str = ""
    依頼病名: str = ""
    依頼コメント: str = ""
    フリーコメント: str = ""
    検体受付日: date | None = None
    検体受付時刻: time | None = None
    報告日: date | None = None
    報告時刻: time | None = None
    検査状況: str = ""


class 検体検査結果(DwhBaseModel):
    """一般検体検査結果（1検査項目につき1レコード）."""

    ROW_ID: str = ""
    親ROW_ID: str = ""
    件数: int = 1
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    採取時年齢: int | None = None
    採取時月齢: int | None = None
    採取時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_採取日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    キャンセル日: date | None = None
    キャンセル時刻: time | None = None
    キャンセル種別: str = ""
    キャンセル理由: str = ""
    入外区分: str = ""
    保険分類: str = ""
    診療科コード: str = ""
    診療科: str = ""
    グループコード: str = ""
    グループ: str = ""
    病棟コード: str = ""
    病棟: str = ""
    採取場所コード: str = ""
    採取場所: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    サブオーナー2の定義: str = ""
    サブオーナー2ID: str = ""
    サブオーナー2: str = ""
    サブオーナー2職種: str = ""
    部門連係ID: str = ""
    検体採取日: date | None = None
    検体採取時刻: time | None = None
    検体提出日: date | None = None
    検体提出時刻: time | None = None
    検体受付日: date | None = None
    検体受付時刻: time | None = None
    報告日: date | None = None
    報告時刻: time | None = None
    検査種別コード: str = ""
    検査種別: str = ""
    検査分類1コード: str = ""
    検査分類1: str = ""
    検査分類2コード: str = ""
    検査分類2: str = ""
    検査分類3コード: str = ""
    検査分類3: str = ""
    至急: str = ""
    検査材料コード: str = ""
    検査材料: str = ""
    容器コード: str = ""
    容器: str = ""
    採取量: float | None = None
    院内院外区分: str = ""
    院外検査委託先コード: str = ""
    院外検査委託先: str = ""
    検査項目コード: str = ""
    検査項目: str = ""
    JLAC10コード: str = ""
    JLAC10名: str = ""
    結果_文字列_: str = ""
    結果_数値_: float | None = None
    結果値単位: str = ""
    結果値コメント: str = ""
    基準値上限_文字列_: str = ""
    基準値下限_文字列_: str = ""
    基準値上限_数値_: float | None = None
    基準値下限_数値_: float | None = None
    異常値: str = ""
    検体コメント: str = ""
    結果画像の有無: str = ""
    負荷量: float | None = None
    画像URL: str = ""
    フリーコメント: str = ""
    検査内容: str = ""


class 細菌検査(DwhBaseModel):
    """細菌検査依頼情報（1オーダー(1材料)につき1レコード）."""

    ROW_ID: str = ""
    件数: int = 1
    シーケンスID: str = ""
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    採取時年齢: int | None = None
    採取時月齢: int | None = None
    採取時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_採取日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日: date | None = None
    キャンセル時刻: time | None = None
    入外区分: str = ""
    保険分類: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    部門連係ID: str = ""
    検体採取日: date | None = None
    検体採取時刻: time | None = None
    検体提出日: date | None = None
    検体提出時刻: time | None = None
    検体受付日: date | None = None
    検体受付時刻: time | None = None
    報告日: date | None = None
    報告時刻: time | None = None
    検査種別コード: str = ""
    検査種別: str = ""
    検査分類1コード: str = ""
    検査分類1: str = ""
    検査材料コード: str = ""
    検査材料: str = ""
    依頼項目数: int | None = None
    依頼項目コード: str = ""
    依頼項目: str = ""
    目的菌コード: str = ""
    目的菌名: str = ""
    感受性希望薬剤コード: str = ""
    感受性希望薬剤: str = ""
    抗酸菌指示薬剤コード: str = ""
    抗酸菌指示薬剤: str = ""
    検査目的コード: str = ""
    検査目的: str = ""
    依頼コメント: str = ""
    基礎疾患コード: str = ""
    基礎疾患: str = ""
    扁平上皮数: int | None = None
    好中球数: int | None = None
    好気血液培養陽性時間: int | None = None
    嫌気血液培養陽性時間: int | None = None
    抗酸菌用血液培養陽性時間: int | None = None
    抗生剤使用の有無: str = ""
    使用中抗生剤コード: str = ""
    使用中抗生剤名: str = ""
    患者症状: str = ""
    塗抹鏡検コメントコード: str = ""
    塗抹鏡検コメント: str = ""
    核酸同定コメントコード: str = ""
    核酸同定コメント: str = ""
    総合コメント: str = ""
    検査状況: str = ""


class 一般細菌塗抹鏡検結果(DwhBaseModel):
    """一般細菌塗抹鏡検結果（1塗抹鏡検につき1レコード(1材料に複数レコード)）."""

    ROW_ID: str = ""
    親ROW_ID: str = ""
    件数: int = 1
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    検索日の定義: str = ""
    検索日_採取日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日: date | None = None
    キャンセル時刻: time | None = None
    入外区分: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    部門連係ID: str = ""
    検体採取日: date | None = None
    検体採取時刻: time | None = None
    検体提出日: date | None = None
    検体提出時刻: time | None = None
    検体受付日: date | None = None
    検体受付時刻: time | None = None
    報告日: date | None = None
    報告時刻: time | None = None
    検査種別コード: str = ""
    検査種別: str = ""
    検査分類1コード: str = ""
    検査分類1: str = ""
    検査材料コード: str = ""
    検査材料: str = ""
    塗抹鏡検項目コード: str = ""
    塗抹鏡検項目: str = ""
    菌量: str = ""
    厚労省菌量コード: str = ""
    結果コメントコード: str = ""
    結果コメント: str = ""


class 一般細菌培養同定検査結果(DwhBaseModel):
    """一般細菌培養同定検査結果（1培養同定検査につき1レコード(1材料に複数レコード)）."""

    ROW_ID: str = ""
    親ROW_ID: str = ""
    件数: int = 1
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    検索日の定義: str = ""
    検索日_採取日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日: date | None = None
    キャンセル時刻: time | None = None
    入外区分: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    部門連係ID: str = ""
    検体採取日: date | None = None
    検体採取時刻: time | None = None
    検体提出日: date | None = None
    検体提出時刻: time | None = None
    検体受付日: date | None = None
    検体受付時刻: time | None = None
    報告日: date | None = None
    報告時刻: time | None = None
    検査種別コード: str = ""
    検査種別: str = ""
    検査分類1コード: str = ""
    検査分類1: str = ""
    検査材料コード: str = ""
    検査材料: str = ""
    菌株No: str = ""
    菌名コード: str = ""
    菌名: str = ""
    菌量: str = ""
    結果コメント: str = ""


class 一般細菌感受性検査結果(DwhBaseModel):
    """一般細菌感受性検査結果（1感受性検査につき1レコード(1菌株に複数レコード)）."""

    ROW_ID: str = ""
    親ROW_ID: str = ""
    件数: int = 1
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    検索日の定義: str = ""
    検索日_採取日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    キャンセル日: date | None = None
    キャンセル時刻: time | None = None
    キャンセル種別: str = ""
    キャンセル理由: str = ""
    入外区分: str = ""
    診療科コード: str = ""
    診療科: str = ""
    グループコード: str = ""
    グループ: str = ""
    病棟コード: str = ""
    病棟: str = ""
    採取場所コード: str = ""
    採取場所: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    サブオーナー2の定義: str = ""
    サブオーナー2ID: str = ""
    サブオーナー2: str = ""
    サブオーナー2職種: str = ""
    部門連係ID: str = ""
    検体採取日: date | None = None
    検体採取時刻: time | None = None
    検体提出日: date | None = None
    検体提出時刻: time | None = None
    検体受付日: date | None = None
    検体受付時刻: time | None = None
    報告日: date | None = None
    報告時刻: time | None = None
    検査種別コード: str = ""
    検査種別: str = ""
    検査分類1コード: str = ""
    検査分類1: str = ""
    検査分類2コード: str = ""
    検査分類2: str = ""
    検査分類3コード: str = ""
    検査分類3: str = ""
    検査材料コード: str = ""
    検査材料: str = ""
    採取部位コード: str = ""
    採取部位: str = ""
    詳細部位コード: str = ""
    詳細部位情報: str = ""
    菌株No: str = ""
    菌名コード: str = ""
    菌名: str = ""
    厚労省菌名コード: str = ""
    菌量コード: str = ""
    菌量: str = ""
    厚労省菌量コード: str = ""
    菌型: str = ""
    注意菌サイン: str = ""
    耐性菌コード: str = ""
    耐性菌名: str = ""
    厚労省耐性菌名コード: str = ""
    菌株保存番号: str = ""
    感受性検査の有無: str = ""
    追加検査の有無: str = ""
    JLAC10コード_感受性_: str = ""
    JLAC10名_感受性_: str = ""
    抗菌薬コード: str = ""
    抗菌薬名: str = ""
    感受性判定コード: str = ""
    感受性判定: str = ""
    MIC値: str = ""


class 一般細菌追加検査結果(DwhBaseModel):
    """コアグラーゼ試験などの一般細菌追加検査結果（1追加検査につき1レコード(1菌株に複数レコード)）."""

    ROW_ID: str = ""


class 抗酸菌塗抹鏡検結果(DwhBaseModel):
    """抗酸菌塗抹鏡検結果（1塗抹鏡検につき1レコード(1材料に複数レコード)）."""

    ROW_ID: str = ""
    親ROW_ID: str = ""
    件数: int = 1
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    検索日の定義: str = ""
    検索日_採取日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日: date | None = None
    キャンセル時刻: time | None = None
    入外区分: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    部門連係ID: str = ""
    検体採取日: date | None = None
    検体採取時刻: time | None = None
    検体提出日: date | None = None
    検体提出時刻: time | None = None
    検体受付日: date | None = None
    検体受付時刻: time | None = None
    報告日: date | None = None
    報告時刻: time | None = None
    検査種別コード: str = ""
    検査種別: str = ""
    検査分類1コード: str = ""
    検査分類1: str = ""
    検査材料コード: str = ""
    検査材料: str = ""
    塗抹鏡検項目コード: str = ""
    塗抹鏡検項目: str = ""
    結果コード: str = ""
    結果: str = ""


class 抗酸菌培養検査結果(DwhBaseModel):
    """抗酸菌培養検査結果（1培養検査につき1レコード(1材料に複数レコード)）."""

    ROW_ID: str = ""
    親ROW_ID: str = ""
    件数: int = 1
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    検索日の定義: str = ""
    検索日_採取日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日: date | None = None
    キャンセル時刻: time | None = None
    入外区分: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    部門連係ID: str = ""
    検体採取日: date | None = None
    検体採取時刻: time | None = None
    検体提出日: date | None = None
    検体提出時刻: time | None = None
    検体受付日: date | None = None
    検体受付時刻: time | None = None
    報告日: date | None = None
    報告時刻: time | None = None
    検査種別コード: str = ""
    検査種別: str = ""
    検査分類1コード: str = ""
    検査分類1: str = ""
    検査材料コード: str = ""
    検査材料: str = ""
    判定日: date | None = None
    日数: int | None = None
    週数: int | None = None
    結果: str = ""
    コロニー数: int | None = None


class 抗酸菌遺伝子検査結果(DwhBaseModel):
    """抗酸菌遺伝子検査結果（1遺伝子検査につき1レコード(1材料に複数レコード)）."""

    ROW_ID: str = ""
    親ROW_ID: str = ""
    件数: int = 1
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    検索日の定義: str = ""
    検索日_採取日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日: date | None = None
    キャンセル時刻: time | None = None
    入外区分: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    採取場所コード: str = ""
    採取場所: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    部門連係ID: str = ""
    検体採取日: date | None = None
    検体採取時刻: time | None = None
    検体提出日: date | None = None
    検体提出時刻: time | None = None
    検体受付日: date | None = None
    検体受付時刻: time | None = None
    報告日: date | None = None
    報告時刻: time | None = None
    検査種別コード: str = ""
    検査種別: str = ""
    検査分類1コード: str = ""
    検査分類1: str = ""
    検査材料コード: str = ""
    検査材料: str = ""
    検査方法コード: str = ""
    検査方法: str = ""
    結果コード: str = ""
    結果: str = ""


class 抗酸菌同定検査結果(DwhBaseModel):
    """抗酸菌同定検査結果（1同定検査につき1レコード(1材料に複数レコード)）."""

    ROW_ID: str = ""
    親ROW_ID: str = ""
    件数: int = 1
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    検索日の定義: str = ""
    検索日_採取日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日: date | None = None
    キャンセル時刻: time | None = None
    入外区分: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    部門連係ID: str = ""
    検体採取日: date | None = None
    検体採取時刻: time | None = None
    検体提出日: date | None = None
    検体提出時刻: time | None = None
    検体受付日: date | None = None
    検体受付時刻: time | None = None
    報告日: date | None = None
    報告時刻: time | None = None
    検査種別コード: str = ""
    検査種別: str = ""
    検査分類1コード: str = ""
    検査分類1: str = ""
    検査材料コード: str = ""
    検査材料: str = ""
    菌株No: str = ""
    菌名コード: str = ""
    菌名: str = ""
    菌量コード: str = ""
    菌量: str = ""


class 抗酸菌感受性結果(DwhBaseModel):
    """抗酸菌感受性検査結果（1感受性検査につき1レコード(1菌株に複数レコード)）."""

    pass


class その他細菌検査結果(DwhBaseModel):
    """簡易同定検査結果、寄生虫検査結果（1検査につき1レコード(1材料に複数レコード)）."""

    ROW_ID: str = ""
    親ROW_ID: str = ""
    件数: int = 1
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    検索日の定義: str = ""
    検索日_採取日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日: date | None = None
    キャンセル時刻: time | None = None
    入外区分: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    部門連係ID: str = ""
    検体採取日: date | None = None
    検体採取時刻: time | None = None
    検体提出日: date | None = None
    検体提出時刻: time | None = None
    検体受付日: date | None = None
    検体受付時刻: time | None = None
    報告日: date | None = None
    報告時刻: time | None = None
    検査種別コード: str = ""
    検査種別: str = ""
    検査分類1コード: str = ""
    検査分類1: str = ""
    検査材料コード: str = ""
    検査材料: str = ""
    検査項目コード: str = ""
    検査項目: str = ""
    結果コード: str = ""
    結果: str = ""


class 病理検査(DwhBaseModel):
    """病理組織検査、細胞診のオーダ・実施情報（1オーダにつき1レコード）."""

    ROW_ID: str = ""
    件数: int = 1
    シーケンスID: str = ""
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    依頼時年齢: int | None = None
    依頼時月齢: int | None = None
    依頼時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_依頼日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日: date | None = None
    キャンセル時刻: time | None = None
    部門発生区分: str = ""
    入外区分: str = ""
    保険分類: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー2の定義: str = ""
    サブオーナー2ID: str = ""
    サブオーナー2: str = ""
    サブオーナー2職種: str = ""
    部門連係ID: str = ""
    検体採取日: date | None = None
    検体採取時刻: time | None = None
    検体提出日: date | None = None
    検体提出時刻: time | None = None
    検体受付日: date | None = None
    検体受付時刻: time | None = None
    報告日: date | None = None
    報告時刻: time | None = None
    緊急区分: str = ""
    検査種別コード: str = ""
    検査種別: str = ""
    検査分類1コード: str = ""
    検査分類1: str = ""
    検査項目コード: str = ""
    検査項目: str = ""
    摘出方法コード: str = ""
    摘出方法: str = ""
    臓器_材料名: str = ""
    依頼病名: str = ""
    検査目的: str = ""
    臨床経過: str = ""
    依頼コメント: str = ""
    検体数: int | None = None
    画像枚数: int | None = None
    喫煙係数: int | None = None
    死産の有無: str = ""
    妊娠週数: int | None = None
    死亡の有無: str = ""
    死亡日: date | None = None
    死亡時刻: time | None = None
    職業: str = ""
    死亡理由: str = ""
    剖検コメント: str = ""
    用量: float | None = None
    病理_標本_番号: str = ""
    状況: str = ""
    レポートURL: str = ""


class 病理検査レポート(DwhBaseModel):
    """病理組織検査、細胞診の診断・所見など。（1検査、1レポートにつき1レコード）."""

    ROW_ID: str = ""
    親ROW_ID: str = ""
    件数: int = 1
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    検索日の定義: str = ""
    検索日_採取日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    キャンセル日: date | None = None
    キャンセル種別: str = ""
    キャンセル理由: str = ""
    入外区分: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー2の定義: str = ""
    サブオーナー2ID: str = ""
    サブオーナー2: str = ""
    サブオーナー2職種: str = ""
    部門連係ID: str = ""
    報告日: date | None = None
    報告時刻: time | None = None
    レポートSEQ: int = 0
    レポート状況: str = ""
    レポート名: str = ""
    第1報告者職種: str = ""
    第1報告者ID: str = ""
    第1報告者: str = ""
    第2報告者職種: str = ""
    第2報告者ID: str = ""
    第2報告者: str = ""
    第3報告者職種: str = ""
    第3報告者ID: str = ""
    第3報告者: str = ""
    第4報告者職種: str = ""
    第4報告者ID: str = ""
    第4報告者: str = ""
    診断: str = ""
    所見: str = ""
    レポートURL: str = ""


class 生理検査(DwhBaseModel):
    """生理検査(呼吸器・脳波・心電図・超音波)オーダ・実施・薬剤材料情報（1検査につき1レコード）."""

    ROW_ID: str = ""
    件数: int = 1
    シーケンスID: str = ""
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    検査時年齢: int | None = None
    検査時月齢: int | None = None
    検査時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_検査日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    キャンセル日: date | None = None
    キャンセル種別: str = ""
    キャンセル理由: str = ""
    部門発生区分: str = ""
    入外区分: str = ""
    保険分類: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー2の定義: str = ""
    サブオーナー2ID: str = ""
    サブオーナー2: str = ""
    サブオーナー2職種: str = ""
    部門連係ID: str = ""
    依頼病名: str = ""
    検査目的: str = ""
    依頼コメント: str = ""
    検査日: date = date(1000, 1, 1)
    検査SEQ: int | None = None
    緊急区分: str = ""
    検査種別コード: str = ""
    検査種別: str = ""
    検査分類1コード: str = ""
    検査分類1: str = ""
    検査項目コード: str = ""
    検査項目: str = ""
    検査部位コード: str = ""
    検査部位: str = ""
    検査部位コメント: str = ""
    検査コメント: str = ""
    レポート依頼の有無: str = ""
    測定時間: int | None = None
    負荷心電図区分: str = ""
    ジキタリス使用の有無: str = ""
    治療前後: str = ""
    乳嘴分泌物1コード: str = ""
    乳嘴分泌物1: str = ""
    乳嘴分泌物2コード: str = ""
    乳嘴分泌物2: str = ""
    同側腋窩リンパ節: str = ""
    Dimpling状態: str = ""
    病変部位コード: str = ""
    病変部位: str = ""
    手技: str = ""
    報告日: date | None = None
    状況: str = ""
    レポートURL: str = ""
    項目SEQ: int = 0
    項目種別: str = ""
    項目コード: str = ""
    項目標準コード: str = ""
    項目名: str = ""
    用量: float | None = None
    単位: str = ""
    ロットNo: str = ""


class 生理検査レポート(DwhBaseModel):
    """生理検査(呼吸器・脳波・心電図・超音波)レポートの診断・所見（1検査につき1レコード）."""

    ROW_ID: str = ""
    親ROW_ID: str = ""
    件数: int = 1
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    検索日の定義: str = ""
    検索日_検査日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    キャンセル日: date | None = None
    キャンセル種別: str = ""
    キャンセル理由: str = ""
    入外区分: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    サブオーナー2の定義: str = ""
    サブオーナー2ID: str = ""
    サブオーナー2: str = ""
    サブオーナー2職種: str = ""
    部門連係ID: str = ""
    依頼病名: str = ""
    検査目的: str = ""
    依頼コメント: str = ""
    検査日: date = date(1000, 1, 1)
    レポートSEQ: int = 0
    レポート状況: str = ""
    レポート名: str = ""
    報告日: date | None = None
    第1報告者職種: str = ""
    第1報告者ID: str = ""
    第1報告者: str = ""
    第2報告者職種: str = ""
    第2報告者ID: str = ""
    第2報告者: str = ""
    第3報告者職種: str = ""
    第3報告者ID: str = ""
    第3報告者: str = ""
    第4報告者職種: str = ""
    第4報告者ID: str = ""
    第4報告者: str = ""
    診断: str = ""
    所見: str = ""
    レポートURL: str = ""


class 内視鏡検査(DwhBaseModel):
    """内視鏡検査オーダ・実施・薬剤材料情報（1検査につき1レコード）."""

    ROW_ID: str = ""
    件数: int = 1
    シーケンスID: str = ""
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    検査時年齢: int | None = None
    検査時月齢: int | None = None
    検査時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_検査日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日: date | None = None
    キャンセル時刻: time | None = None
    部門発生区分: str = ""
    入外区分: str = ""
    保険分類: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー2の定義: str = ""
    サブオーナー2ID: str = ""
    サブオーナー2: str = ""
    サブオーナー2職種: str = ""
    部門連係ID: str = ""
    依頼病名: str = ""
    検査目的: str = ""
    依頼コメント: str = ""
    検査日: date = date(1000, 1, 1)
    緊急区分: str = ""
    検査SEQ: int | None = None
    検査種別コード: str = ""
    検査種別: str = ""
    検査分類1コード: str = ""
    検査分類1: str = ""
    検査項目コード: str = ""
    検査項目: str = ""
    検査部位コード: str = ""
    検査部位: str = ""
    検査部位コメント: str = ""
    検査コメント: str = ""
    レポート依頼の有無: str = ""
    治療承諾書の有無: str = ""
    告知の有無: str = ""
    抗凝固血小板療法の有無: str = ""
    呼吸不全の有無: str = ""
    薬剤過敏症の有無: str = ""
    抗凝固剤使用の有無: str = ""
    抗コリン剤筋注の可否: str = ""
    グルカゴン静注の可否: str = ""
    注意すべき薬品: str = ""
    ECG検査依頼の有無: str = ""
    血液ガス依頼の有無: str = ""
    凝固機能検査の有無: str = ""
    報告日: date | None = None
    状況: str = ""
    レポートURL: str = ""
    手技コード: str = ""
    手技標準コード: str = ""
    手技: str = ""
    項目種別: str = ""
    項目コード: str = ""
    項目標準コード: str = ""
    項目名: str = ""
    用量: float | None = None
    単位: str = ""
    ロットNo: str = ""


class 内視鏡検査レポート(DwhBaseModel):
    """内視鏡検査レポート情報(所見など)（1検査につき1レコード）."""

    ROW_ID: str = ""
    親ROW_ID: str = ""
    件数: int = 1
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    検索日の定義: str = ""
    検索日_検査日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    キャンセル日: date | None = None
    キャンセル種別: str = ""
    キャンセル理由: str = ""
    入外区分: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    サブオーナー2の定義: str = ""
    サブオーナー2ID: str = ""
    サブオーナー2: str = ""
    サブオーナー2職種: str = ""
    部門連係ID: str = ""
    検査日: date = date(1000, 1, 1)
    レポートSEQ: int = 0
    レポート状況: str = ""
    レポート名: str = ""
    報告日: date | None = None
    第1報告者職種: str = ""
    第1報告者ID: str = ""
    第1報告者: str = ""
    第2報告者職種: str = ""
    第2報告者ID: str = ""
    第2報告者: str = ""
    第3報告者職種: str = ""
    第3報告者ID: str = ""
    第3報告者: str = ""
    第4報告者職種: str = ""
    第4報告者ID: str = ""
    第4報告者: str = ""
    診断: str = ""
    所見: str = ""
    レポートURL: str = ""


class 放射線検査(DwhBaseModel):
    """放射線検査オーダ・実施・薬剤材料情報（1検査につき1レコード）."""

    pass


class 放射線検査オーダー(DwhBaseModel):
    """放射線検査オーダ・実施（1検査につき1レコード）."""

    ROW_ID: str = ""
    件数: int = 1
    シーケンスID: str = ""
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    検査時年齢: int | None = None
    検査時月齢: int | None = None
    検査時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_検査日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    キャンセル日: date | None = None
    キャンセル種別: str = ""
    キャンセル理由: str = ""
    部門発生区分: str = ""
    入外区分: str = ""
    保険分類: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    サブオーナー2の定義: str = ""
    サブオーナー2ID: str = ""
    サブオーナー2: str = ""
    サブオーナー2職種: str = ""
    部門連係ID: str = ""
    依頼病名: str = ""
    検査目的: str = ""
    検査内容: str = ""
    依頼コメント: str = ""
    検査SEQ: int | None = None
    検査日: date = date(1000, 1, 1)
    緊急区分: str = ""
    検査項目コード: str = ""
    検査項目名: str = ""
    検査種別コード: str = ""
    検査種別: str = ""
    検査分類1コード: str = ""
    検査分類1: str = ""
    部位コード: str = ""
    検査部位: str = ""
    手技コード: str = ""
    手技: str = ""
    方向コード: str = ""
    方向: str = ""
    修飾コード: str = ""
    修飾: str = ""
    検査コメント: str = ""
    レポート依頼の有無: str = ""
    報告日: date | None = None
    検査状況: str = ""
    レポートURL: str = ""
    画像URL: str = ""


class 放射線検査薬剤(DwhBaseModel):
    """放射線検査オーダ・実施・薬剤情報（1検査につきNレコード）."""

    ROW_ID: str = ""
    件数: int = 1
    シーケンスID: str = ""
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    検査時年齢: int | None = None
    検査時月齢: int | None = None
    検査時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_検査日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    キャンセル日: date | None = None
    キャンセル種別: str = ""
    キャンセル理由: str = ""
    部門発生区分: str = ""
    入外区分: str = ""
    保険分類: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    サブオーナー2の定義: str = ""
    サブオーナー2ID: str = ""
    サブオーナー2: str = ""
    サブオーナー2職種: str = ""
    部門連係ID: str = ""
    依頼病名: str = ""
    検査目的: str = ""
    検査内容: str = ""
    依頼コメント: str = ""
    検査SEQ: int | None = None
    検査日: date = date(1000, 1, 1)
    緊急区分: str = ""
    検査項目コード: str = ""
    検査項目名: str = ""
    検査種別コード: str = ""
    検査種別: str = ""
    検査分類1コード: str = ""
    検査分類1: str = ""
    部位コード: str = ""
    検査部位: str = ""
    手技コード: str = ""
    手技標準コード: str = ""
    手技: str = ""
    方向コード: str = ""
    方向: str = ""
    修飾コード: str = ""
    修飾: str = ""
    検査コメント: str = ""
    レポート依頼の有無: str = ""
    報告日: date | None = None
    検査状況: str = ""
    レポートURL: str = ""
    画像URL: str = ""
    項目種別: str = ""
    項目コード: str = ""
    項目標準コード: str = ""
    項目名: str = ""
    用量: float | None = None
    単位: str = ""
    分割数: int | None = None
    ロットNo: str = ""


class 放射線検査材料(DwhBaseModel):
    """放射線検査オーダ・実施・材料情報（1検査につきNレコード）."""

    ROW_ID: str = ""
    件数: int = 1
    シーケンスID: str = ""
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    検査時年齢: int | None = None
    検査時月齢: int | None = None
    検査時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_検査日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    キャンセル日: date | None = None
    キャンセル種別: str = ""
    キャンセル理由: str = ""
    部門発生区分: str = ""
    入外区分: str = ""
    保険分類: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    サブオーナー2の定義: str = ""
    サブオーナー2ID: str = ""
    サブオーナー2: str = ""
    サブオーナー2職種: str = ""
    部門連係ID: str = ""
    依頼病名: str = ""
    検査目的: str = ""
    検査内容: str = ""
    依頼コメント: str = ""
    検査SEQ: int | None = None
    検査日: date = date(1000, 1, 1)
    緊急区分: str = ""
    検査項目コード: str = ""
    検査項目名: str = ""
    検査種別コード: str = ""
    検査種別: str = ""
    検査分類1コード: str = ""
    検査分類1: str = ""
    部位コード: str = ""
    検査部位: str = ""
    手技コード: str = ""
    手技標準コード: str = ""
    手技: str = ""
    方向コード: str = ""
    方向: str = ""
    修飾コード: str = ""
    修飾: str = ""
    検査コメント: str = ""
    レポート依頼の有無: str = ""
    報告日: date | None = None
    検査状況: str = ""
    レポートURL: str = ""
    画像URL: str = ""
    項目種別: str = ""
    項目コード: str = ""
    項目標準コード: str = ""
    項目名: str = ""
    用量: float | None = None
    単位: str = ""
    分割数: int | None = None
    ロットNo: str = ""


class 放射線検査レポート(DwhBaseModel):
    """放射線検査レポート(所見など)（1検査につき1レコード）."""

    ROW_ID: str = ""
    親ROW_ID: str = ""
    件数: int = 1
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    検索日の定義: str = ""
    検索日_検査日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    キャンセル日: date | None = None
    キャンセル種別: str = ""
    キャンセル理由: str = ""
    入外区分: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    サブオーナー2の定義: str = ""
    サブオーナー2ID: str = ""
    サブオーナー2: str = ""
    サブオーナー2職種: str = ""
    部門連係ID: str = ""
    検査日: date = date(1000, 1, 1)
    レポートSEQ: int = 0
    レポート状況: str = ""
    レポート名: str = ""
    報告日: date | None = None
    第1報告者職種: str = ""
    第1報告者ID: str = ""
    第1報告者: str = ""
    第2報告者職種: str = ""
    第2報告者ID: str = ""
    第2報告者: str = ""
    第3報告者職種: str = ""
    第3報告者ID: str = ""
    第3報告者: str = ""
    第4報告者職種: str = ""
    第4報告者ID: str = ""
    第4報告者: str = ""
    診断: str = ""
    所見: str = ""
    レポートURL: str = ""


class RI検査(DwhBaseModel):
    """RI検査オーダ・実施・薬剤材料情報（1検査につき1レコード）."""

    ROW_ID: str = ""
    件数: int = 1
    シーケンスID: str = ""
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    検査時年齢: int | None = None
    検査時月齢: int | None = None
    検査時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_検査日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    キャンセル日: date | None = None
    キャンセル種別: str = ""
    キャンセル理由: str = ""
    部門発生区分: str = ""
    入外区分: str = ""
    保険分類: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    サブオーナー2の定義: str = ""
    サブオーナー2ID: str = ""
    サブオーナー2: str = ""
    サブオーナー2職種: str = ""
    部門連係ID: str = ""
    検査日: date = date(1000, 1, 1)
    放射線検査標準コード: str = ""
    放射線検査標準名: str = ""
    緊急区分: str = ""
    検査種別コード: str = ""
    検査種別: str = ""
    依頼病名: str = ""
    検査目的: str = ""
    検査内容: str = ""
    依頼コメント: str = ""
    検査項目コード: str = ""
    検査項目名: str = ""
    部位コード: str = ""
    検査部位: str = ""
    予約数: int | None = None
    予約初期数: int | None = None
    処方薬剤数: int | None = None
    詳細指示数: int | None = None
    身長: float | None = None
    体重: float | None = None
    体重単位: str = ""
    依頼コード: str = ""
    機能検査コード: str = ""
    機能検査: str = ""
    撮影部位コード: str = ""
    検査部位セット: str = ""
    検査状況: str = ""
    レポートURL: str = ""
    項目種別: str = ""
    項目コード: str = ""
    項目名: str = ""
    用量: float | None = None
    単位: str = ""
    分割数: int | None = None
    ロットNo: str = ""


class RI検査レポート(DwhBaseModel):
    """RI検査レポート情報(所見など)（1検査につき1レコード）."""

    ROW_ID: str = ""
    親ROW_ID: str = ""
    件数: int = 1
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    検索日の定義: str = ""
    検索日_検査日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    キャンセル日: date | None = None
    キャンセル種別: str = ""
    キャンセル理由: str = ""
    入外区分: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    サブオーナー2の定義: str = ""
    サブオーナー2ID: str = ""
    サブオーナー2: str = ""
    サブオーナー2職種: str = ""
    部門連係ID: str = ""
    検査日: date = date(1000, 1, 1)
    レポートSEQ: int = 0
    レポート状況: str = ""
    レポート名: str = ""
    報告日: date | None = None
    第1報告者職種: str = ""
    第1報告者ID: str = ""
    第1報告者: str = ""
    第2報告者職種: str = ""
    第2報告者ID: str = ""
    第2報告者: str = ""
    第3報告者職種: str = ""
    第3報告者ID: str = ""
    第3報告者: str = ""
    第4報告者職種: str = ""
    第4報告者ID: str = ""
    第4報告者: str = ""
    診断: str = ""
    所見: str = ""
    レポートURL: str = ""


class 抗酸菌感受性検査結果(DwhBaseModel):
    """抗酸菌感受性検査結果."""

    ROW_ID: str = ""
    親ROW_ID: str = ""
    件数: int = 1
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    検索日の定義: str = ""
    検索日_採取日_: date = date(1000, 1, 1)
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    キャンセル日: date | None = None
    キャンセル時刻: time | None = None
    キャンセル種別: str = ""
    キャンセル理由: str = ""
    入外区分: str = ""
    診療科コード: str = ""
    診療科: str = ""
    グループコード: str = ""
    グループ: str = ""
    病棟コード: str = ""
    病棟: str = ""
    採取場所コード: str = ""
    採取場所: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    サブオーナー2の定義: str = ""
    サブオーナー2ID: str = ""
    サブオーナー2: str = ""
    サブオーナー2職種: str = ""
    部門連係ID: str = ""
    検体採取日: date | None = None
    検体採取時刻: time | None = None
    検体提出日: date | None = None
    検体提出時刻: time | None = None
    検体受付日: date | None = None
    検体受付時刻: time | None = None
    報告日: date | None = None
    報告時刻: time | None = None
    検査種別コード: str = ""
    検査種別: str = ""
    検査分類1コード: str = ""
    検査分類1: str = ""
    検査分類2コード: str = ""
    検査分類2: str = ""
    検査分類3コード: str = ""
    検査分類3: str = ""
    検査材料コード: str = ""
    検査材料: str = ""
    採取部位コード: str = ""
    採取部位: str = ""
    詳細部位コード: str = ""
    詳細部位情報: str = ""
    菌株No: str = ""
    菌名コード: str = ""
    菌名: str = ""
    厚労省菌名コード: str = ""
    菌量コード: str = ""
    菌量: str = ""
    厚労省菌量コード: str = ""
    検査方法コード: str = ""
    検査方法: str = ""
    JLAC10コード_培養_: str = ""
    JLAC10名_培養_: str = ""
    結果コード: str = ""
    結果: str = ""
    菌株保存番号: str = ""
    感受性検査の有無: str = ""
    MIC検査の有無: str = ""
    抗菌薬コード: str = ""
    抗菌薬名: str = ""
    感受性判定コード: str = ""
    感受性判定: str = ""
    MIC値: str = ""
    厚労省MIC値: str = ""
    結果コメントコード: str = ""
    結果コメント: str = ""
