"""自動生成されたDWHテーブルモデル."""

from __future__ import annotations

from datetime import date, time
from decimal import Decimal
from pydantic import Field

from interactive_ehr.models._base import DwhBaseModel


class 処方(DwhBaseModel):
    """処方情報（1薬剤につき1レコード）."""

    ROW_ID: str = ""
    件数: int = 1
    シーケンスID: str = ""
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    服薬開始時年齢: int | None = None
    服薬開始時月齢: int | None = None
    服薬時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_服薬開始日_: date = Field(date(1000, 1, 1), alias="検索日(服薬開始日)")
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    キャンセル日: date | None = None
    キャンセル種別: str = ""
    キャンセル理由: str = ""
    入外区分: str = ""
    保険分類: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    部門連係ID: str = ""
    院内院外区分: str = ""
    時間外_休日区分: str = Field("", alias="時間外・休日区分")
    服薬開始日: date = date(1000, 1, 1)
    服薬終了日: date | None = None
    RP番号: int = 0
    薬剤数: int | None = None
    一回量: float | None = None
    一回量単位: str = ""
    一日回数: int | None = None
    一日量: float | None = None
    一日量単位: str = ""
    処方日数: int | None = None
    処方期間_日数_: int | None = Field(None, alias="処方期間(日数)")
    指示用量: float | None = None
    指示単位: str = ""
    指示総量: float | None = None
    第一単位量: float | None = None
    第一単位: str = ""
    第一単位総量: float | None = None
    医事換算単位量: float | None = None
    医事換算単位: str = ""
    医事換算単位総量: float | None = None
    成分単位量: float | None = None
    成分単位総量: float | None = None
    用法: str = ""
    用法種別: str = ""
    処置薬剤: str = ""
    不均等指示の有無: str = ""
    依頼コメント_患者_: str = Field("", alias="依頼コメント(患者)")
    依頼コメント_医事_: str = Field("", alias="依頼コメント(医事)")
    依頼コメント_薬剤部_: str = Field("", alias="依頼コメント(薬剤部)")
    薬剤SEQ: int = 0
    分類1コード: str = ""
    分類1: str = ""
    分類2コード: str = ""
    分類2: str = ""
    薬剤コード: str = ""
    薬剤名: str = ""
    成分名: str = ""
    薬価基準収載医薬品コード: str = ""
    HOTコード: str = ""
    剤型コード: str = ""
    剤型名: str = ""
    薬効コード: str = ""
    薬効名: str = ""
    麻薬対象: str = ""
    ハイリスク薬対象: str = ""
    治験薬対象: str = ""
    抗がん剤対象: str = ""
    後発医薬品対象: str = ""
    後発医薬品の有無: str = ""
    後発医薬品への変更可否: str = ""
    一般名処方: str = ""
    粉砕不可対象: str = ""
    分割不可対象: str = ""
    用法コメント: str = ""
    処方コメント: str = ""
    レジメンID: str = ""
    レジメンバージョン: int | None = None
    レジメンセット名: str = ""
    実施状況: str | None = None
    依頼日: date | None = None
    中止フラグ: str | None = None
    長期収載品選定理由: str = ""


class 処方指示(DwhBaseModel):
    """処方指示情報（1薬剤ごとに1レコード）."""

    ROW_ID: str = ""
    件数: int = 1
    シーケンスID: str = ""
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    服薬開始時年齢: int | None = None
    服薬開始時月齢: int | None = None
    服薬時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_服薬開始日_: date = Field(date(1000, 1, 1), alias="検索日(服薬開始日)")
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    キャンセル日: date | None = None
    キャンセル種別: str = ""
    キャンセル理由: str = ""
    入外区分: str = ""
    保険分類: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    部門連係ID: str = ""
    院内院外区分: str = ""
    時間外_休日区分: str = Field("", alias="時間外・休日区分")
    服薬開始日: date = date(1000, 1, 1)
    服薬終了日: date | None = None
    RP番号: int = 0
    薬剤数: int | None = None
    一回量: float | None = None
    一日回数: int | None = None
    一日量: float | None = None
    一日量単位: str = ""
    処方日数: int | None = None
    処方期間_日数_: int | None = Field(None, alias="処方期間(日数)")
    指示用量: float | None = None
    指示単位: str = ""
    指示総量: float | None = None
    第一単位量: float | None = None
    第一単位: str = ""
    第一単位総量: float | None = None
    医事換算単位量: float | None = None
    医事換算単位: str = ""
    医事換算単位総量: float | None = None
    成分単位量: float | None = None
    成分単位総量: float | None = None
    用法: str = ""
    用法種別: str = ""
    処置薬剤: str = ""
    不均等指示の有無: str = ""
    依頼コメント_患者_: str = Field("", alias="依頼コメント(患者)")
    依頼コメント_医事_: str = Field("", alias="依頼コメント(医事)")
    依頼コメント_薬剤部_: str = Field("", alias="依頼コメント(薬剤部)")
    薬剤SEQ: int = 0
    分類1コード: str = ""
    分類1: str = ""
    分類2コード: str = ""
    分類2: str = ""
    薬剤コード: str = ""
    薬剤名: str = ""
    成分名: str = ""
    薬価基準収載医薬品コード: str = ""
    HOTコード: str = ""
    剤型コード: str = ""
    剤型名: str = ""
    薬効コード: str = ""
    薬効名: str = ""
    麻薬対象: str = ""
    ハイリスク薬対象: str = ""
    治験薬対象: str = ""
    抗がん剤対象: str = ""
    後発医薬品対象: str = ""
    後発医薬品の有無: str = ""
    後発医薬品への変更可否: str = ""
    一般名処方: str = ""
    粉砕不可対象: str = ""
    分割不可対象: str = ""
    用法コメント: str = ""
    処方コメント: str = ""
    レジメンID: str = ""
    レジメンバージョン: int | None = None
    レジメンセット名: str = ""
    依頼日: date | None = None
    中止フラグ: str | None = None
    指示タイプ: str | None = None


class 処方実施(DwhBaseModel):
    """処方実施情報（1薬剤ごとに1レコード）."""

    ROW_ID: str = ""
    件数: int = 1
    シーケンスID: str = ""
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    服薬時年齢: int | None = None
    服薬時月齢: int | None = None
    服薬時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_服用実施日_: date = Field(date(1000, 1, 1), alias="検索日(服用実施日)")
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    キャンセル日: date | None = None
    キャンセル種別: str = ""
    キャンセル理由: str = ""
    入外区分: str = ""
    保険分類: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    部門連係ID: str = ""
    実施予定日: date | None = None
    実施タイミングコード: str | None = None
    実施タイミング: str | None = None
    有効フラグ: str | None = None
    準備フラグ: str | None = None
    ハイリスク薬フラグ: str | None = None
    実施ステータス: str | None = None
    入力用量: int | None = None
    入力単位: str | None = None
    選択単位番号: str | None = None
    第一単位量: float | None = None
    第一単位: str = ""
    医事換算単位量: float | None = None
    医事換算単位: str = ""
    医事換算単位総量: float | None = None
    成分単位量: float | None = None
    成分単位総量: float | None = None
    薬剤コード: str = ""
    薬剤名: str = ""
    成分名: str = ""
    後発医薬品対象: str = ""
    後発医薬品の有無: str = ""
    後発医薬品への変更可否: str = ""
    一般名処方: str = ""
    長期収載品選定理由: str = ""
    指示タイプ: str | None = None


class 注射指示(DwhBaseModel):
    """注射指示情報（1薬剤ごとに1レコード）."""

    ROW_ID: str = ""
    件数: int = 1
    シーケンスID: str = ""
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    実施時年齢: int | None = None
    実施時月齢: int | None = None
    実施時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_実施日_: date = Field(date(1000, 1, 1), alias="検索日(実施日)")
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    キャンセル日: date | None = None
    キャンセル種別: str = ""
    キャンセル理由: str = ""
    入外区分: str = ""
    保険分類: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    部門連係ID: str = ""
    予定開始日: date | None = None
    予定開始時刻: time | None = None
    予定終了日: date | None = None
    予定終了時刻: time | None = None
    RP番号: int = 0
    薬剤数: int | None = None
    回数SEQ: int | None = None
    手技区分: str = ""
    手技コード: str = ""
    手技名: str = ""
    用法内容: str = ""
    精密持続点滴加算対象: str = ""
    無菌製剤対象: str = ""
    頓用投与条件: str = ""
    頓用コメント: str = ""
    手技別コメント: str = ""
    手技別コメント_器具_: str = Field("", alias="手技別コメント(器具)")
    依頼コメント: str = ""
    薬剤SEQ: int = 0
    薬剤コード: str = ""
    薬剤名: str = ""
    成分名: str = ""
    薬価基準収載医薬品コード: str = ""
    HOTコード: str = ""
    剤型コード: str = ""
    剤型名: str = ""
    薬効コード: str = ""
    薬効名: str = ""
    指示用量: float | None = None
    指示単位: str = ""
    指示総量: float | None = None
    第一単位量: float | None = None
    第一単位: str = ""
    第一単位総量: float | None = None
    医事換算単位量: float | None = None
    医事換算単位: str = ""
    医事換算単位総量: float | None = None
    成分単位量: float | None = None
    成分単位: str = ""
    成分単位総量: float | None = None
    点滴速度: float | None = None
    注入時間: float | None = None
    麻薬対象: str = ""
    ハイリスク薬対象: str = ""
    抗がん剤対象: str = ""
    治験薬対象: str = ""
    後発医薬品対象: str = ""
    後発医薬品の有無: str = ""
    注射開始日: date = date(1000, 1, 1)
    注射開始時刻: time | None = None
    注射終了日: date | None = None
    注射終了時刻: time | None = None
    実施状況: str = ""
    レジメンID: str = ""
    レジメンバージョン: int | None = None
    レジメンセット名: str = ""
    ラベル: str | None = None


class 注射実施(DwhBaseModel):
    """注射実施情報（1薬剤ごとに1レコード）."""

    ROW_ID: str = ""
    件数: int = 1
    シーケンスID: str = ""
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    実施時年齢: int | None = None
    実施時月齢: int | None = None
    実施時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_実施日_: date = Field(date(1000, 1, 1), alias="検索日(実施日)")
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    キャンセル日: date | None = None
    キャンセル種別: str = ""
    キャンセル理由: str = ""
    入外区分: str = ""
    保険分類: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    実施場所コード: str = ""
    実施場所: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    部門連係ID: str = ""
    予定開始日: date | None = None
    予定開始時刻: time | None = None
    注射実施開始日: date = date(1000, 1, 1)
    注射実施開始時刻: time | None = None
    注射実施開始者ID: str = ""
    注射実施開始者: str = ""
    注射実施開始者職種: str = ""
    混合日: date | None = None
    混合時刻: time | None = None
    照合日: date | None = None
    照合時刻: time | None = None
    照合者ID1: str = ""
    照合者1: str = ""
    照合者職種1: str = ""
    照合者ID2: str = ""
    照合者2: str = ""
    照合者職種2: str = ""
    注射終了日: date | None = None
    注射終了時刻: time | None = None
    注射実施終了者ID: str = ""
    注射実施終了者: str = ""
    注射実施終了者職種: str = ""
    RP番号: int = 0
    薬剤数: int | None = None
    回数SEQ: int | None = None
    手技区分: str = ""
    手技コード: str = ""
    手技名: str = ""
    用法内容: str = ""
    精密持続点滴加算対象: str = ""
    無菌製剤対象: str = ""
    頓用投与条件: str = ""
    頓用コメント: str = ""
    手技別コメント: str = ""
    手技別コメント_器具_: str = Field("", alias="手技別コメント(器具)")
    依頼コメント: str = ""
    薬剤SEQ: int = 0
    薬剤コード: str = ""
    薬剤名: str = ""
    成分名: str = ""
    薬価基準収載医薬品コード: str = ""
    HOTコード: str = ""
    剤型コード: str = ""
    剤型名: str = ""
    薬効コード: str = ""
    薬効名: str = ""
    実施用量: float | None = None
    実施単位: str = ""
    実施総量: float | None = None
    第一単位量: float | None = None
    第一単位: str = ""
    第一単位総量: float | None = None
    医事換算単位量: float | None = None
    医事換算単位: str = ""
    医事換算単位総量: float | None = None
    成分単位量: float | None = None
    成分単位: str = ""
    成分単位総量: float | None = None
    点滴速度: float | None = None
    注入時間: float | None = None
    麻薬対象: str = ""
    ハイリスク薬対象: str = ""
    抗がん剤対象: str = ""
    治験薬対象: str = ""
    後発医薬品対象: str = ""
    後発医薬品の有無: str = ""
    レジメンID: str = ""
    レジメンバージョン: int | None = None
    レジメンセット名: str = ""
    実施状況: str = ""
    注射実施日: date | None = None
    実施時間: time | None = None
    ラベル: str | None = None


class 処置(DwhBaseModel):
    """手技、器材、薬剤、加算の単位（1手技、1器材、1薬剤、1加算ごとに各1レコード）."""

    ROW_ID: str = ""
    件数: int = 1
    シーケンスID: str = ""
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    実施時年齢: int | None = None
    実施時月齢: int | None = None
    実施時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_実施開始日_: date = Field(date(1000, 1, 1), alias="検索日(実施開始日)")
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    キャンセル種別: str = ""
    キャンセル理由: str = ""
    入外区分: str = ""
    保険分類: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    サブオーナー2の定義: str = ""
    サブオーナー2ID: str = ""
    サブオーナー2: str = ""
    サブオーナー2職種: str = ""
    部門連係ID: str = ""
    登録オーダー種別: str = ""
    実施場所コード: str = ""
    実施場所: str = ""
    RP番号: int = 0
    回数SEQ: int = 0
    手技区分: str = ""
    手技コード: str = ""
    手技: str = ""
    項目種別: str = ""
    項目コード: str = ""
    項目名: str = ""
    指示用量: float | None = None
    指示総量: float | None = None
    指示第一単位量: float | None = None
    指示第一単位総量: float | None = None
    指示医事換算単位量: float | None = None
    指示医事換算単位総量: float | None = None
    指示成分単位量: float | None = None
    指示成分単位総量: float | None = None
    実施用量: float | None = None
    実施総量: float | None = None
    実施第一単位量: float | None = None
    実施第一単位総量: float | None = None
    実施医事換算単位量: float | None = None
    実施医事換算単位総量: float | None = None
    実施成分単位量: float | None = None
    実施成分単位総量: float | None = None
    ロス用量: float | None = None
    依頼コメント: str = ""
    実施状況: str = ""
    実施医師ID: str = ""
    実施医師: str = ""
    実施看護師ID: str = ""
    実施看護師: str = ""
    実施開始日: date = date(1000, 1, 1)
    実施開始時刻: time | None = None
    実施終了日: date | None = None
    実施終了時刻: time | None = None


class 歯科処置(DwhBaseModel):
    """歯科処置の手技、器材、薬剤、加算の単位（1手技、1器材、1薬剤、1加算ごとに各1レコード）."""

    ROW_ID: str = ""
    件数: int = 1
    シーケンスID: str = ""
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    実施時年齢: int | None = None
    実施時月齢: int | None = None
    実施時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_実施開始日_: date = Field(date(1000, 1, 1), alias="検索日(実施開始日)")
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    キャンセル種別: str = ""
    キャンセル理由: str = ""
    入外区分: str = ""
    保険分類: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    サブオーナー2の定義: str = ""
    サブオーナー2ID: str = ""
    サブオーナー2: str = ""
    サブオーナー2職種: str = ""
    登録オーダー種別: str = ""
    実施場所コード: str = ""
    実施場所: str = ""
    RP番号: int = 0
    回数SEQ: int = 0
    手技区分: str = ""
    手技コード: str = ""
    手技: str = ""
    項目種別: str = ""
    項目コード: str = ""
    歯式1: str = ""
    項目名: str = ""
    指示用量: float | None = None
    指示第一単位量: float | None = None
    指示第一単位総量: float | None = None
    指示医事換算単位量: float | None = None
    指示医事換算単位総量: float | None = None
    指示成分単位量: float | None = None
    指示成分単位総量: float | None = None
    実施用量: float | None = None
    実施第一単位量: float | None = None
    実施第一単位総量: float | None = None
    実施医事換算単位量: float | None = None
    実施医事換算単位総量: float | None = None
    実施成分単位量: float | None = None
    実施成分単位総量: float | None = None
    ロス用量: float | None = None
    依頼コメント: str = ""
    実施状況: str = ""
    実施医師ID: str = ""
    実施医師: str = ""
    実施看護師ID: str = ""
    実施看護師: str = ""
    実施開始日: date = date(1000, 1, 1)
    実施開始時刻: time | None = None
    実施終了日: date | None = None
    実施終了時刻: time | None = None


class 手術依頼(DwhBaseModel):
    """手術依頼内容（1手術につき1レコード）."""

    ROW_ID: str = ""
    件数: int = 1
    シーケンスID: str = ""
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    予定時年齢: int | None = None
    予定時月齢: int | None = None
    予定時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_手術予定日_: date = Field(date(1000, 1, 1), alias="検索日(手術予定日)")
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    キャンセル日: date | None = None
    キャンセル種別: str = ""
    キャンセル理由: str = ""
    入外区分: str = ""
    保険分類: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    部門連係ID: str = ""
    依頼種別: str = ""
    枠連数: int | None = None
    申込術式1コード: str = ""
    申込術式1: str = ""
    申込術式2コード: str = ""
    申込術式2: str = ""
    申込術式3コード: str = ""
    申込術式3: str = ""
    申込術式4コード: str = ""
    申込術式4: str = ""
    申込術式5コード: str = ""
    申込術式5: str = ""
    申込術式6コード: str = ""
    申込術式6: str = ""
    申込術式7コード: str = ""
    申込術式7: str = ""
    申込術式8コード: str = ""
    申込術式8: str = ""
    申込術式9コード: str = ""
    申込術式9: str = ""
    申込術式10コード: str = ""
    申込術式10: str = ""
    申込術式ICD9CM1: str = ""
    申込術式ICD9CM2: str = ""
    申込術式ICD9CM3: str = ""
    申込術式ICD9CM4: str = ""
    申込術式ICD9CM5: str = ""
    申込術式ICD9CM6: str = ""
    申込術式ICD9CM7: str = ""
    申込術式ICD9CM8: str = ""
    申込術式ICD9CM9: str = ""
    申込術式ICD9CM10: str = ""
    予定体位1コード: str = ""
    予定体位1: str = ""
    予定体位2コード: str = ""
    予定体位2: str = ""
    予定体位3コード: str = ""
    予定体位3: str = ""
    予定体位4コード: str = ""
    予定体位4: str = ""
    予定体位5コード: str = ""
    予定体位5: str = ""
    予定体位6コード: str = ""
    予定体位6: str = ""
    麻酔科依頼の有無: str = ""
    予定麻酔科医1ID: str = ""
    予定麻酔科医1: str = ""
    予定麻酔科医2ID: str = ""
    予定麻酔科医2: str = ""
    予定麻酔科医3ID: str = ""
    予定麻酔科医3: str = ""
    予定麻酔科医4ID: str = ""
    予定麻酔科医4: str = ""
    全麻対象: str = ""
    局麻対象: str = ""
    硬麻対象: str = ""
    腰麻対象: str = ""
    伝麻対象: str = ""
    静麻対象: str = ""
    ICU入院の有無: str = ""
    ICU入院希望日数: int | None = None
    HCU入院の有無: str = ""
    HCU入院希望日数: int | None = None
    予定入室日時: time | None = None
    予定手術開始日時: time | None = None
    予定手術終了日時: time | None = None
    予定手術所要時間_分_: int | None = Field(None, alias="予定手術所要時間(分)")
    予定退室日時: time | None = None
    予定手術室滞在時間_分_: int | None = Field(None, alias="予定手術室滞在時間(分)")
    予定術者1ID: str = ""
    予定術者1: str = ""
    予定術者2ID: str = ""
    予定術者2: str = ""
    予定術者3ID: str = ""
    予定術者3: str = ""
    予定術者4ID: str = ""
    予定術者4: str = ""
    予定術者5ID: str = ""
    予定術者5: str = ""
    予定術者6ID: str = ""
    器械出し看護師1ID: str = ""
    器械出し看護師1: str = ""
    器械出し看護師2ID: str = ""
    器械出し看護師2: str = ""
    器械出し看護師3ID: str = ""
    器械出し看護師3: str = ""
    器械出し看護師4ID: str = ""
    器械出し看護師4: str = ""
    器械出し看護師5ID: str = ""
    器械出し看護師5: str = ""
    予定特殊機材1コード: str = ""
    予定特殊機材1: str = ""
    予定特殊機材2コード: str = ""
    予定特殊機材2: str = ""
    予定特殊機材3コード: str = ""
    予定特殊機材3: str = ""
    予定特殊機材4コード: str = ""
    予定特殊機材4: str = ""
    予定特殊機材5コード: str = ""
    予定特殊機材5: str = ""
    予定特殊機材6コード: str = ""
    予定特殊機材6: str = ""
    予定特殊機材7コード: str = ""
    予定特殊機材7: str = ""
    予定特殊機材8コード: str = ""
    予定特殊機材8: str = ""
    予定特殊機材9コード: str = ""
    予定特殊機材9: str = ""
    予定特殊機材10コード: str = ""
    予定特殊機材10: str = ""
    予定特殊機材11コード: str = ""
    予定特殊機材11: str = ""
    予定特殊機材12コード: str = ""
    予定特殊機材12: str = ""
    予定特殊機材13コード: str = ""
    予定特殊機材13: str = ""
    予定特殊機材14コード: str = ""
    予定特殊機材14: str = ""
    予定特殊機材15コード: str = ""
    予定特殊機材15: str = ""
    予定術中検査1コード: str = ""
    予定術中検査1: str = ""
    予定術中検査2コード: str = ""
    予定術中検査2: str = ""
    予定術中検査3コード: str = ""
    予定術中検査3: str = ""
    予定術中検査4コード: str = ""
    予定術中検査4: str = ""
    予定術中検査5コード: str = ""
    予定術中検査5: str = ""
    予定術中検査6コード: str = ""
    予定術中検査6: str = ""
    予定術中検査7コード: str = ""
    予定術中検査7: str = ""
    予定術中検査8コード: str = ""
    予定術中検査8: str = ""
    予定術中検査9コード: str = ""
    予定術中検査9: str = ""
    予定術中検査10コード: str = ""
    予定術中検査10: str = ""
    予定術中検査11コード: str = ""
    予定術中検査11: str = ""
    予定術中検査12コード: str = ""
    予定術中検査12: str = ""
    予定術中検査13コード: str = ""
    予定術中検査13: str = ""
    予定術中検査14コード: str = ""
    予定術中検査14: str = ""
    予定術中検査15コード: str = ""
    予定術中検査15: str = ""
    希望事項コメント: str = ""
    依頼病名: str = ""
    予定手術室コード: str = ""
    予定手術室: str = ""
    予定出血量: int | None = None
    輸血申込の有無: str = ""
    予定輸血種別コード1: str | None = None
    予定輸血種別名1: str | None = None
    予定輸血量1: int | None = None
    予定輸血種別コード2: str | None = None
    予定輸血種別名2: str | None = None
    予定輸血量2: int | None = None
    予定輸血種別コード3: str | None = None
    予定輸血種別名3: str | None = None
    予定輸血量3: int | None = None
    予定輸血種別コード4: str | None = None
    予定輸血種別名4: str | None = None
    予定輸血量4: int | None = None
    予定輸血種別コード5: str | None = None
    予定輸血種別名5: str | None = None
    予定輸血量5: int | None = None
    予定輸血種別コード6: str | None = None
    予定輸血種別名6: str | None = None
    予定輸血量6: int | None = None
    予定輸血種別コード7: str | None = None
    予定輸血種別名7: str | None = None
    予定輸血量7: int | None = None
    予定輸血種別コード8: str | None = None
    予定輸血種別名8: str | None = None
    予定輸血量8: int | None = None
    予定輸血種別コード9: str | None = None
    予定輸血種別名9: str | None = None
    予定輸血量9: int | None = None
    予定輸血種別コード10: str | None = None
    予定輸血種別名10: str | None = None
    予定輸血量10: int | None = None
    EGC異常の有無: str = ""
    心エコー異常の有無: str = ""
    胸部X_P異常の有無: str = Field("", alias="胸部X-P異常の有無")
    筋_骨格疾患の有無: str = Field("", alias="筋・骨格疾患の有無")
    内分泌疾患の有無: str = ""
    脳血管障害の有無: str = ""
    他院手術歴の有無: str = ""
    他院手術日: date | None = None
    他院手術コメント: str = ""
    全身状態: str = ""
    合併症: str = ""
    特殊薬剤コメント: str = ""
    コメントコード_複数_: str = Field("", alias="コメントコード(複数)")
    コメント: str = ""
    依頼コメント: str = ""
    アレルギーコメント: str = ""
    現病歴_現症: str = Field("", alias="現病歴・現症")
    実施状況: str = ""


class 手術実施(DwhBaseModel):
    """手術実施（1手術につき1レコード）."""

    ROW_ID: str = ""
    件数: int = 1
    シーケンスID: str = ""
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    実施時年齢: int | None = None
    実施時月齢: int | None = None
    実施時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_手術実施日_: date = Field(date(1000, 1, 1), alias="検索日(手術実施日)")
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    キャンセル日: date | None = None
    キャンセル種別: str = ""
    キャンセル理由: str = ""
    入外区分: str = ""
    保険分類: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    部門連係ID: str = ""
    主治医ID: str = ""
    主治医: str = ""
    入室日時: time | None = None
    退室日時: time | None = None
    手術室滞在時間_分_: int | None = Field(None, alias="手術室滞在時間(分)")
    麻酔開始日時: time | None = None
    麻酔終了日時: time | None = None
    麻酔時間_分_: int | None = Field(None, alias="麻酔時間(分)")
    手術開始日時: time | None = None
    手術終了日時: time | None = None
    手術所要時間_分_: int | None = Field(None, alias="手術所要時間(分)")
    回復室入室日時: time | None = None
    回復室退室日時: time | None = None
    回復室滞在時間_分_: int | None = Field(None, alias="回復室滞在時間(分)")
    手術予定所要時間_分_: int | None = Field(None, alias="手術予定所要時間(分)")
    手術実施科コード: str = ""
    手術実施科: str = ""
    手術室コード: str = ""
    手術室名: str = ""
    手術区分: str = ""
    病名1コード: str = ""
    病名1: str = ""
    病名2コード: str = ""
    病名2: str = ""
    病名3コード: str = ""
    病名3: str = ""
    病名4コード: str = ""
    病名4: str = ""
    病名5コード: str = ""
    病名5: str = ""
    合併症1コード: str = ""
    合併症1: str = ""
    合併症2コード: str = ""
    合併症2: str = ""
    合併症3コード: str = ""
    合併症3: str = ""
    合併症4コード: str = ""
    合併症4: str = ""
    合併症5コード: str = ""
    合併症5: str = ""
    術式1コード: str = ""
    実施術式1: str = ""
    術式2コード: str = ""
    実施術式2: str = ""
    術式3コード: str = ""
    実施術式3: str = ""
    術式4コード: str = ""
    実施術式4: str = ""
    術式5コード: str = ""
    実施術式5: str = ""
    術式6コード: str = ""
    実施術式6: str = ""
    術式7コード: str = ""
    実施術式7: str = ""
    術式8コード: str = ""
    実施術式8: str = ""
    術式9コード: str = ""
    実施術式9: str = ""
    術式10コード: str = ""
    実施術式10: str = ""
    実施術式ICD9CM1: str = ""
    実施術式ICD9CM2: str = ""
    実施術式ICD9CM3: str = ""
    実施術式ICD9CM4: str = ""
    実施術式ICD9CM5: str = ""
    実施術式ICD9CM6: str = ""
    実施術式ICD9CM7: str = ""
    実施術式ICD9CM8: str = ""
    実施術式ICD9CM9: str = ""
    実施術式ICD9CM10: str = ""
    部位1コード: str = ""
    部位1: str = ""
    部位2コード: str = ""
    部位2: str = ""
    部位3コード: str = ""
    部位3: str = ""
    部位4コード: str = ""
    部位4: str = ""
    部位5コード: str = ""
    部位5: str = ""
    部位6コード: str = ""
    部位6: str = ""
    部位7コード: str = ""
    部位7: str = ""
    部位8コード: str = ""
    部位8: str = ""
    部位9コード: str = ""
    部位9: str = ""
    部位10コード: str = ""
    部位10: str = ""
    体位1コード: str = ""
    体位1: str = ""
    体位2コード: str = ""
    体位2: str = ""
    体位3コード: str = ""
    体位3: str = ""
    体位4コード: str = ""
    体位4: str = ""
    体位5コード: str = ""
    体位5: str = ""
    体位6コード: str = ""
    体位6: str = ""
    術者ID_執刀医_: str = Field("", alias="術者ID(執刀医)")
    術者_執刀医_: str = Field("", alias="術者(執刀医)")
    術者1ID: str = ""
    術者1: str = ""
    術者2ID: str = ""
    術者2: str = ""
    術者3ID: str = ""
    術者3: str = ""
    術者4ID: str = ""
    術者4: str = ""
    器械出し看護師1ID: str = ""
    器械出し看護師1: str = ""
    器械出し看護師2ID: str = ""
    器械出し看護師2: str = ""
    器械出し看護師3ID: str = ""
    器械出し看護師3: str = ""
    器械出し看護師4ID: str = ""
    器械出し看護師4: str = ""
    器械出し看護師5ID: str = ""
    器械出し看護師5: str = ""
    器械出し看護師6ID: str = ""
    器械出し看護師6: str = ""
    器械出し看護師7ID: str = ""
    器械出し看護師7: str = ""
    器械出し看護師8ID: str = ""
    器械出し看護師8: str = ""
    器械出し看護師9ID: str = ""
    器械出し看護師9: str = ""
    器械出し看護師10ID: str = ""
    器械出し看護師10: str = ""
    外回り看護師1ID: str = ""
    外回り看護師1: str = ""
    外回り看護師2ID: str = ""
    外回り看護師2: str = ""
    外回り看護師3ID: str = ""
    外回り看護師3: str = ""
    外回り看護師4ID: str = ""
    外回り看護師4: str = ""
    外回り看護師5ID: str = ""
    外回り看護師5: str = ""
    外回り看護師6ID: str = ""
    外回り看護師6: str = ""
    外回り看護師7ID: str = ""
    外回り看護師7: str = ""
    外回り看護師8ID: str = ""
    外回り看護師8: str = ""
    外回り看護師9ID: str = ""
    外回り看護師9: str = ""
    外回り看護師10ID: str = ""
    外回り看護師10: str = ""
    麻酔科依頼の有無: str = ""
    麻酔科医1ID: str = ""
    麻酔科医1: str = ""
    麻酔医1担当区分: str = ""
    麻酔科医2ID: str = ""
    麻酔科医2: str = ""
    麻酔医2担当区分: str = ""
    麻酔科医3ID: str = ""
    麻酔科医3: str = ""
    麻酔医3担当区分: str = ""
    麻酔科医4ID: str = ""
    麻酔科医4: str = ""
    麻酔医4担当区分: str = ""
    麻酔科医5ID: str = ""
    麻酔科医5: str = ""
    麻酔医5担当区分: str = ""
    麻酔科指導医1ID: str = ""
    麻酔科指導医1: str = ""
    麻酔科指導医2ID: str = ""
    麻酔科指導医2: str = ""
    麻酔科指導医3ID: str = ""
    麻酔科指導医3: str = ""
    全麻対象: str = ""
    局麻対象: str = ""
    硬麻対象: str = ""
    腰麻対象: str = ""
    伝麻対象: str = ""
    静麻対象: str = ""
    実出血量: int | None = None
    輸血1コード: str = ""
    輸血種別名1: str | None = None
    術中輸血量1: int | None = None
    輸血2コード: str = ""
    輸血種別名2: str | None = None
    術中輸血量2: int | None = None
    輸血3コード: str = ""
    輸血種別名3: str | None = None
    術中輸血量3: int | None = None
    輸血4コード: str = ""
    輸血種別名4: str | None = None
    術中輸血量4: int | None = None
    輸血5コード: str = ""
    輸血種別名5: str | None = None
    術中輸血量5: int | None = None
    輸血6コード: str = ""
    輸血種別名6: str | None = None
    術中輸血量6: int | None = None
    輸血7コード: str = ""
    輸血種別名7: str | None = None
    術中輸血量7: int | None = None
    輸血8コード: str = ""
    輸血種別名8: str | None = None
    術中輸血量8: int | None = None
    輸血9コード: str = ""
    輸血種別名9: str | None = None
    術中輸血量9: int | None = None
    輸血10コード: str = ""
    輸血種別名10: str | None = None
    術中輸血量10: int | None = None
    輸血総量: int | None = None
    輸液1コード: str = ""
    輸液名1: str | None = None
    輸液1量: int | None = None
    輸液2コード: str = ""
    輸液名2: str | None = None
    輸液2量: int | None = None
    輸液3コード: str = ""
    輸液名3: str | None = None
    輸液3量: int | None = None
    輸液4コード: str = ""
    輸液名4: str | None = None
    輸液4量: int | None = None
    輸液5コード: str = ""
    輸液名5: str | None = None
    輸液総量: int | None = None
    尿量: int | None = None
    薬品1コード: str = ""
    薬品1: str = ""
    薬品2コード: str = ""
    薬品2: str = ""
    薬品3コード: str = ""
    薬品3: str = ""
    薬品4コード: str = ""
    薬品4: str = ""
    薬品5コード: str = ""
    薬品5: str = ""
    薬品6コード: str = ""
    薬品6: str = ""
    薬品7コード: str = ""
    薬品7: str = ""
    薬品8コード: str = ""
    薬品8: str = ""
    薬品9コード: str = ""
    薬品9: str = ""
    薬品10コード: str = ""
    薬品10: str = ""
    薬剤コメント: str = ""
    全身状態: str = ""
    アレルギー有無: str = ""
    術中コメント: str = ""


class 手術材料等(DwhBaseModel):
    """手術材料（1材料につき1レコード）."""

    ROW_ID: str = ""
    親ROW_ID: str = ""
    件数: int = 1
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    実施時年齢: int | None = None
    実施時月齢: int | None = None
    実施時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_手術実施日_: date = Field(date(1000, 1, 1), alias="検索日(手術実施日)")
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    キャンセル日: date | None = None
    キャンセル種別: str = ""
    キャンセル理由: str = ""
    入外区分: str = ""
    保険分類: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    部門連係ID: str = ""
    手術開始日: date = date(1000, 1, 1)
    手術開始時刻: time | None = None
    手術終了日: date | None = None
    手術終了時刻: time | None = None
    項目種別: str = ""
    項目コード: str = ""
    商品名: str = ""
    規格: str = ""
    有効期限日: date | None = None
    使用数量: float | None = None
    使用単位: str = ""
    メーカー: str = ""


class 手術記録(DwhBaseModel):
    """手術記録情報(術式・麻酔時間・輸血量など)（1手術につき1レコード）."""

    ROW_ID: str = ""
    件数: int = 1
    シーケンスID: str = ""
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    手術開始時年齢: int | None = None
    手術開始時月齢: int | None = None
    手術開始時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_手術開始日_: date = Field(date(1000, 1, 1), alias="検索日(手術開始日)")
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日_TOPERCD: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    キャンセル理由: str = ""
    入外区分: str = ""
    保険分類: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    部門連係ID: str = ""
    手術区分: str = ""
    手術開始日: date = date(1000, 1, 1)
    手術開始時刻: time | None = None
    手術終了日: date | None = None
    手術終了時刻: time | None = None
    手術所要時間: int | None = None
    術者1ID: str = ""
    術者1: str = ""
    術者2ID: str = ""
    術者2: str = ""
    術者3ID: str = ""
    術者3: str = ""
    術者4ID: str = ""
    術者4: str = ""
    術者5ID: str = ""
    術者5: str = ""
    術者6ID: str = ""
    術者6: str = ""
    助手1ID: str = ""
    助手1: str = ""
    助手2ID: str = ""
    助手2: str = ""
    助手3ID: str = ""
    助手3: str = ""
    助手4ID: str = ""
    助手4: str = ""
    助手5ID: str = ""
    助手5: str = ""
    麻酔医1ID: str = ""
    麻酔医1: str = ""
    麻酔医2ID: str = ""
    麻酔医2: str = ""
    麻酔医3ID: str = ""
    麻酔医3: str = ""
    麻酔医4ID: str = ""
    麻酔医4: str = ""
    麻酔医5ID: str = ""
    麻酔医5: str = ""
    看護師1ID: str = ""
    看護師1: str = ""
    看護師2ID: str = ""
    看護師2: str = ""
    看護師3ID: str = ""
    看護師3: str = ""
    看護師4ID: str = ""
    看護師4: str = ""
    看護師5ID: str = ""
    看護師5: str = ""
    予定術式1コード: str = ""
    予定術式1: str = ""
    予定術式2コード: str = ""
    予定術式2: str = ""
    予定術式3コード: str = ""
    予定術式3: str = ""
    予定術式4コード: str = ""
    予定術式4: str = ""
    予定術式5コード: str = ""
    予定術式5: str = ""
    予定術式6コード: str = ""
    予定術式6: str = ""
    予定術式7コード: str = ""
    予定術式7: str = ""
    予定術式8コード: str = ""
    予定術式8: str = ""
    予定術式9コード: str = ""
    予定術式9: str = ""
    予定術式10コード: str = ""
    予定術式10: str = ""
    予定術式ICD9CM1: str = ""
    予定術式ICD9CM2: str = ""
    予定術式ICD9CM3: str = ""
    予定術式ICD9CM4: str = ""
    予定術式ICD9CM5: str = ""
    予定術式ICD9CM6: str = ""
    予定術式ICD9CM7: str = ""
    予定術式ICD9CM8: str = ""
    予定術式ICD9CM9: str = ""
    予定術式ICD9CM10: str = ""
    実施術式1コード: str = ""
    実施術式1: str = ""
    実施術式2コード: str = ""
    実施術式2: str = ""
    実施術式3コード: str = ""
    実施術式3: str = ""
    実施術式4コード: str = ""
    実施術式4: str = ""
    実施術式5コード: str = ""
    実施術式5: str = ""
    実施術式6コード: str = ""
    実施術式6: str = ""
    実施術式7コード: str = ""
    実施術式7: str = ""
    実施術式8コード: str = ""
    実施術式8: str = ""
    実施術式9コード: str = ""
    実施術式9: str = ""
    実施術式10コード: str = ""
    実施術式10: str = ""
    実施術式ICD9CM1: str = ""
    実施術式ICD9CM2: str = ""
    実施術式ICD9CM3: str = ""
    実施術式ICD9CM4: str = ""
    実施術式ICD9CM5: str = ""
    実施術式ICD9CM6: str = ""
    実施術式ICD9CM7: str = ""
    実施術式ICD9CM8: str = ""
    実施術式ICD9CM9: str = ""
    実施術式ICD9CM10: str = ""
    体位1コード: str = ""
    体位1: str = ""
    体位2コード: str = ""
    体位2: str = ""
    体位3コード: str = ""
    体位3: str = ""
    体位4コード: str = ""
    体位4: str = ""
    体位5コード: str = ""
    体位5: str = ""
    体位6コード: str = ""
    体位6: str = ""
    術前診断病名1コード: str = ""
    術前診断病名2コード: str = ""
    術前診断病名3コード: str = ""
    術前診断病名: str = ""
    手術診断病名1コード: str = ""
    手術診断病名2コード: str = ""
    手術診断病名3コード: str = ""
    手術診断病名4コード: str = ""
    手術診断病名5コード: str = ""
    手術診断: str = ""
    麻酔1コード: str = ""
    麻酔1名: str = ""
    麻酔1時間_分_: int | None = Field(None, alias="麻酔1時間(分)")
    麻酔前投与薬1: str = ""
    麻酔薬1: str = ""
    麻酔1効果: str = ""
    麻酔2時間_分_: int | None = Field(None, alias="麻酔2時間(分)")
    麻酔3時間_分_: int | None = Field(None, alias="麻酔3時間(分)")
    麻酔4時間_分_: int | None = Field(None, alias="麻酔4時間(分)")
    麻酔5時間_分_: int | None = Field(None, alias="麻酔5時間(分)")
    麻酔6時間_分_: int | None = Field(None, alias="麻酔6時間(分)")
    麻酔7時間_分_: int | None = Field(None, alias="麻酔7時間(分)")
    麻酔8時間_分_: int | None = Field(None, alias="麻酔8時間(分)")
    麻酔9時間_分_: int | None = Field(None, alias="麻酔9時間(分)")
    麻酔10時間_分_: int | None = Field(None, alias="麻酔10時間(分)")
    出血量: int | None = None
    尿量: int | None = None
    輸血種別1コード: str = ""
    輸血種別名1: str | None = None
    輸血1量: int | None = None
    輸血種別2コード: str = ""
    輸血種別名2: str | None = None
    輸血2量: int | None = None
    輸血種別3コード: str = ""
    輸血種別名3: str | None = None
    輸血3量: int | None = None
    輸血種別4コード: str = ""
    輸血種別名4: str | None = None
    輸血4量: int | None = None
    輸血種別5コード: str = ""
    輸血種別名5: str | None = None
    輸血5量: int | None = None
    輸血種別6コード: str = ""
    輸血種別名6: str | None = None
    輸血6量: int | None = None
    輸血種別7コード: str = ""
    輸血種別名7: str | None = None
    輸血7量: int | None = None
    輸血種別8コード: str = ""
    輸血種別名8: str | None = None
    輸血8量: int | None = None
    輸血種別9コード: str = ""
    輸血種別名9: str | None = None
    輸血9量: int | None = None
    輸血種別10コード: str = ""
    輸血種別名10: str | None = None
    輸血10量: int | None = None
    総輸血量: int | None = None
    輸液情報: str = ""
    総輸液量: int | None = None
    入力日_TEMRIDX: date | None = None


class 手術所見(DwhBaseModel):
    """手術所見内容（1記事につき1レコード）."""

    ROW_ID: str = ""
    件数: int = 1
    シーケンスID: str = ""
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    記載時年齢: int | None = None
    記載時月齢: int | None = None
    記載時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_記載日_: date = Field(date(1000, 1, 1), alias="検索日(記載日)")
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    キャンセル日: date | None = None
    キャンセル時刻: time | None = None
    入外区分: str = ""
    保険分類: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    記載日: date = date(1000, 1, 1)
    記載時刻: time | None = None
    確定日: date | None = None
    承認日: date | None = None
    記事種別コード: str = ""
    記事種別: str = ""
    記事連番: int = 0
    記事内表示連番: int | None = None
    記事データ種別コード: str = ""
    記事データ種別: str = ""
    記事: str = ""
    未整形記事の有無: str = ""
    記事_未整形_: str = Field("", alias="記事(未整形)")
    プロブレム: str = ""
    実施状況: str = ""
    実施状況コード: str | None = None


class 輸血実施(DwhBaseModel):
    """輸血実施内容（1血液製剤につき1レコード）."""

    pass


class 透析実施(DwhBaseModel):
    """透析実施内容（1透析につき1レコード）."""

    ROW_ID: str = ""
    件数: int = 1
    シーケンスID: str = ""
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: Decimal = Decimal("0")
    透析開始時年齢: int | None = None
    透析開始時月齢: int | None = None
    透析開始時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_透析実施日_: date = Field(date(1000, 1, 1), alias="検索日(透析実施日)")
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル種別: str = ""
    キャンセル理由: str = ""
    入外区分: str = ""
    保険分類: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    サブオーナー2の定義: str = ""
    サブオーナー2ID: str = ""
    サブオーナー2: str = ""
    サブオーナー2職種: str = ""
    部門連係ID: str = ""
    指示適用開始日: date | None = None
    指示適用終了日: date | None = None
    透析曜日区分: str | None = None
    指示日: date | None = None
    指示者コード: str | None = None
    指示者: str | None = None
    傷病名: str | None = None
    実施場所: str | None = None
    D_W_: int | None = Field(None, alias="D.W.")
    予定治療装置コード1: str | None = None
    予定治療装置識別ID1: str | None = None
    予定治療装置1: str | None = None
    予定治療装置コード2: str | None = None
    予定治療装置識別ID2: str | None = None
    予定治療装置2: str | None = None
    予定治療装置コード3: str | None = None
    予定治療装置識別ID3: str | None = None
    予定治療装置3: str | None = None
    予定治療装置コード4: str | None = None
    予定治療装置識別ID4: str | None = None
    予定治療装置4: str | None = None
    予定治療装置コード5: str | None = None
    予定治療装置識別ID5: str | None = None
    予定治療装置5: str | None = None
    予定治療時間1: str | None = None
    予定治療時間2: str | None = None
    予定治療時間3: str | None = None
    予定治療時間4: str | None = None
    予定治療時間5: str | None = None
    受持ち看護師ID: str | None = None
    受持ち看護師: str | None = None
    治療回数: int | None = None
    ベッド番号コード: str | None = None
    ベッド番号: str | None = None
    AMPM: str | None = None
    開始時刻: time | None = None
    終了時刻: time | None = None
    治療時間: int | None = None
    ブラッドアクセス選択コード1: str | None = None
    ブラッドアクセス1: str | None = None
    ブラッドアクセス選択コード2: str | None = None
    ブラッドアクセス2: str | None = None
    治療方法コード1: str | None = None
    治療方法1: str | None = None
    治療方法コード2: str | None = None
    治療方法2: str | None = None
    治療方法コード3: str | None = None
    治療方法3: str | None = None
    治療方法コード4: str | None = None
    治療方法4: str | None = None
    治療方法コード5: str | None = None
    治療方法5: str | None = None
    治療方法その他名称: str | None = None
    治療装置コード1: str | None = None
    治療装置識別ID1: str | None = None
    治療装置1: str | None = None
    治療装置コード2: str | None = None
    治療装置識別ID2: str | None = None
    治療装置2: str | None = None
    治療装置コード3: str | None = None
    治療装置識別ID3: str | None = None
    治療装置3: str | None = None
    治療装置コード4: str | None = None
    治療装置識別ID4: str | None = None
    治療装置4: str | None = None
    治療装置コード5: str | None = None
    治療装置識別ID5: str | None = None
    治療装置5: str | None = None
    治療時間1: str | None = None
    使用膜1_1: str | None = None
    二次膜1: str | None = None
    使用膜2_1: str | None = None
    処理量1: Decimal | None = None
    処理量単位1: str | None = None
    血液流量1: Decimal | None = None
    透析液コード1: str | None = None
    透析液1: str | None = None
    透析液量1: Decimal | None = None
    透析液量単位1: str | None = None
    透析液流量1: Decimal | None = None
    透析液温度1: str | None = None
    置換液コード1: str | None = None
    置換液1: str | None = None
    置換量1: Decimal | None = None
    置換量単位1: str | None = None
    置換液流量1: Decimal | None = None
    置換液温度1: str | None = None
    補液コード1: str | None = None
    補液1: str | None = None
    補液量1: Decimal | None = None
    補液量単位1: str | None = None
    補液流量1: Decimal | None = None
    補液温度1: str | None = None
    抗凝固薬コード1: str | None = None
    抗凝固薬1: str | None = None
    前投与量1: Decimal | None = None
    前投与量単位1: str | None = None
    持続投与速度A側1: Decimal | None = None
    持続投与速度A側単位1: str | None = None
    持続投与速度V側1: Decimal | None = None
    持続投与速度V側単位1: str | None = None
    持続総量1: Decimal | None = None
    持続総量単位1: str | None = None
    停止時間1: Decimal | None = None
    治療時間2: str | None = None
    使用膜1_2: str | None = None
    二次膜2: str | None = None
    使用膜2_2: str | None = None
    処理量2: Decimal | None = None
    処理量単位2: str | None = None
    血液流量2: Decimal | None = None
    透析液コード2: str | None = None
    透析液2: str | None = None
    透析液量2: Decimal | None = None
    透析液量単位2: str | None = None
    透析液流量2: Decimal | None = None
    透析液温度2: str | None = None
    置換液コード2: str | None = None
    置換液2: str | None = None
    置換量2: Decimal | None = None
    置換量単位2: str | None = None
    置換液流量2: Decimal | None = None
    置換液温度2: str | None = None
    補液コード2: str | None = None
    補液2: str | None = None
    補液量2: Decimal | None = None
    補液量単位2: str | None = None
    補液流量2: Decimal | None = None
    補液温度2: str | None = None
    抗凝固薬コード2: str | None = None
    抗凝固薬2: str | None = None
    前投与量2: Decimal | None = None
    前投与量単位2: str | None = None
    持続投与速度A側2: Decimal | None = None
    持続投与速度A側単位2: str | None = None
    持続投与速度V側2: Decimal | None = None
    持続投与速度V側単位2: str | None = None
    持続総量2: Decimal | None = None
    持続総量単位2: str | None = None
    停止時間2: Decimal | None = None
    治療時間3: str | None = None
    使用膜1_3: str | None = None
    二次膜3: str | None = None
    使用膜2_3: str | None = None
    処理量3: Decimal | None = None
    処理量単位3: str | None = None
    血液流量3: Decimal | None = None
    透析液コード3: str | None = None
    透析液3: str | None = None
    透析液量3: Decimal | None = None
    透析液量単位3: str | None = None
    透析液流量3: Decimal | None = None
    透析液温度3: str | None = None
    置換液コード3: str | None = None
    置換液3: str | None = None
    置換量3: Decimal | None = None
    置換量単位3: str | None = None
    置換液流量3: Decimal | None = None
    置換液温度3: str | None = None
    補液コード3: str | None = None
    補液3: str | None = None
    補液量3: Decimal | None = None
    補液量単位3: str | None = None
    補液流量3: Decimal | None = None
    補液温度3: str | None = None
    抗凝固薬コード3: str | None = None
    抗凝固薬3: str | None = None
    前投与量3: Decimal | None = None
    前投与量単位3: str | None = None
    持続投与速度A側3: Decimal | None = None
    持続投与速度A側単位3: str | None = None
    持続投与速度V側3: Decimal | None = None
    持続投与速度V側単位3: str | None = None
    持続総量3: Decimal | None = None
    持続総量単位3: str | None = None
    停止時間3: Decimal | None = None
    治療時間4: str | None = None
    使用膜1_4: str | None = None
    二次膜4: str | None = None
    使用膜2_4: str | None = None
    処理量4: Decimal | None = None
    処理量単位4: str | None = None
    血液流量4: Decimal | None = None
    透析液コード4: str | None = None
    透析液4: str | None = None
    透析液量4: Decimal | None = None
    透析液量単位4: str | None = None
    透析液流量4: Decimal | None = None
    透析液温度4: str | None = None
    置換液コード4: str | None = None
    置換液4: str | None = None
    置換量4: Decimal | None = None
    置換量単位4: str | None = None
    置換液流量4: Decimal | None = None
    置換液温度4: str | None = None
    補液コード4: str | None = None
    補液4: str | None = None
    補液量4: Decimal | None = None
    補液量単位4: str | None = None
    補液流量4: Decimal | None = None
    補液温度4: str | None = None
    抗凝固薬コード4: str | None = None
    抗凝固薬4: str | None = None
    前投与量4: Decimal | None = None
    前投与量単位4: str | None = None
    持続投与速度A側4: Decimal | None = None
    持続投与速度A側単位4: str | None = None
    持続投与速度V側4: Decimal | None = None
    持続投与速度V側単位4: str | None = None
    持続総量4: Decimal | None = None
    持続総量単位4: str | None = None
    停止時間4: Decimal | None = None
    治療時間5: str | None = None
    使用膜1_5: str | None = None
    二次膜5: str | None = None
    使用膜2_5: str | None = None
    処理量5: Decimal | None = None
    処理量単位5: str | None = None
    血液流量5: Decimal | None = None
    透析液コード5: str | None = None
    透析液5: str | None = None
    透析液量5: Decimal | None = None
    透析液量単位5: str | None = None
    透析液流量5: Decimal | None = None
    透析液温度5: str | None = None
    置換液コード5: str | None = None
    置換液5: str | None = None
    置換量5: Decimal | None = None
    置換量単位5: str | None = None
    置換液流量5: Decimal | None = None
    置換液温度5: str | None = None
    補液コード5: str | None = None
    補液5: str | None = None
    補液量5: Decimal | None = None
    補液量単位5: str | None = None
    補液流量5: Decimal | None = None
    補液温度5: str | None = None
    抗凝固薬コード5: str | None = None
    抗凝固薬5: str | None = None
    前投与量5: Decimal | None = None
    前投与量単位5: str | None = None
    持続投与速度A側5: Decimal | None = None
    持続投与速度A側単位5: str | None = None
    持続投与速度V側5: Decimal | None = None
    持続投与速度V側単位5: str | None = None
    持続総量5: Decimal | None = None
    持続総量単位5: str | None = None
    停止時間5: Decimal | None = None
    前回後体重: Decimal | None = None
    前体重: Decimal | None = None
    目標体重: Decimal | None = None
    総除水量: Decimal | None = None
    算出記入者コード: str | None = None
    算出記入者: str | None = None
    算出確認者コード: str | None = None
    算出確認者: str | None = None
    回路_返血生食: Decimal | None = Field(None, alias="回路・返血生食")
    食事: int | None = None
    点滴: int | None = None
    昼食: int | None = None
    加算項目1: str | None = None
    加算量1: int | None = None
    加算項目2: str | None = None
    加算量2: int | None = None
    加算項目3: str | None = None
    加算量3: int | None = None
    加算項目4: str | None = None
    加算量4: int | None = None
    加算項目5: str | None = None
    加算量5: int | None = None
    加算項目6: str | None = None
    加算量6: int | None = None
    ドレーン: int | None = None
    尿: int | None = None
    便: int | None = None
    減算項目1: str | None = None
    減算量1: int | None = None
    減算項目2: str | None = None
    減算量2: int | None = None
    後体重: Decimal | None = None
    治療日: date | None = None
    移動方法コード: str | None = None
    移動方法: str | None = None
    体重測定方法コード: str | None = None
    体重測定方法: str | None = None
    担当者コード: str | None = None
    担当者: str | None = None
    確認者コード: str | None = None
    確認者: str | None = None
    CTR: int | None = None
    回路確認者コード1: str | None = None
    回路確認者1: str | None = None
    回路確認者コード2: str | None = None
    回路確認者2: str | None = None
    運転確認者コード1: str | None = None
    運転確認者1: str | None = None
    運転確認者コード2: str | None = None
    運転確認者2: str | None = None
    開始時医師コード: str | None = None
    開始時医師: str | None = None
    開始時看護師コード1: str | None = None
    開始時看護師1: str | None = None
    開始時看護師コード2: str | None = None
    開始時看護師2: str | None = None
    開始時シャント音コード: str | None = None
    開始時シャント音: str | None = None
    開始時スリルコード: str | None = None
    開始時スリル: str | None = None
    開始時穿刺コード_A_: str | None = Field(None, alias="開始時穿刺コード(A)")
    開始時穿刺_A_: str | None = Field(None, alias="開始時穿刺(A)")
    開始時穿刺コード_V_: str | None = Field(None, alias="開始時穿刺コード(V)")
    開始時穿刺_V_: str | None = Field(None, alias="開始時穿刺(V)")
    開始時カテーテル名称コード: str | None = None
    開始時カテーテル名称: str | None = None
    開始時カテーテル位置コード1: str | None = None
    開始時カテーテル位置1: str | None = None
    開始時カテーテル状態コード1: str | None = None
    開始時カテーテル状態1: str | None = None
    開始時カテーテル位置コード2: str | None = None
    開始時カテーテル位置2: str | None = None
    開始時カテーテル状態コード2: str | None = None
    開始時カテーテル状態2: str | None = None
    開始時UKカテーテルコメント: str | None = None
    開始時採血有無フラグ: str | None = None
    開始時採血本数: int | None = None
    開始時血液流量: int | None = None
    開始時透析液変更フラグ: str | None = None
    開始時透析液流量: int | None = None
    終了時看護師コード1: str | None = None
    終了時看護師1: str | None = None
    終了時看護師コード2: str | None = None
    終了時看護師2: str | None = None
    終了時採血有無フラグ: str | None = None
    終了時採血本数: int | None = None
    終了時圧迫止血フラグ_Ns_: str | None = Field(None, alias="終了時圧迫止血フラグ(Ns)")
    終了時圧迫止血フラグ_自己_: str | None = Field(
        None, alias="終了時圧迫止血フラグ(自己)"
    )
    終了時カテーテル名称コード: str | None = None
    終了時カテーテル名称: str | None = None
    終了時カテーテル位置コード1: str | None = None
    終了時カテーテル位置1: str | None = None
    終了時カテーテル状態コード1: str | None = None
    終了時カテーテル状態1: str | None = None
    終了時カテーテル位置コード2: str | None = None
    終了時カテーテル位置2: str | None = None
    終了時カテーテル状態コード2: str | None = None
    終了時カテーテル状態2: str | None = None
    終了時UKカテーテルコメント: str | None = None
    終了時シャント音コード: str | None = None
    終了時シャント音: str | None = None
    終了時スリルコード: str | None = None
    終了時スリル: str | None = None
    終了時残血コード_A_: str | None = Field(None, alias="終了時残血コード(A)")
    終了時残血_A_: str | None = Field(None, alias="終了時残血(A)")
    終了時残血コード_V_: str | None = Field(None, alias="終了時残血コード(V)")
    終了時残血_V_: str | None = Field(None, alias="終了時残血(V)")
    終了時残血コード_ダイアライザー_: str | None = Field(
        None, alias="終了時残血コード(ダイアライザー)"
    )
    終了時ロック: str | None = None
    終了時ロックその他: str | None = None
    終了時残血_ダイアライザー_: str | None = Field(
        None, alias="終了時残血(ダイアライザー)"
    )
    施行者コード: str | None = None
    施行者: str | None = None
    薬剤コード1: str | None = None
    薬剤1: str | None = None
    用量1: Decimal | None = None
    単位コード1: str | None = None
    単位1: str | None = None
    薬剤コード2: str | None = None
    薬剤2: str | None = None
    用量2: Decimal | None = None
    単位コード2: str | None = None
    単位2: str | None = None
    薬剤コード3: str | None = None
    薬剤3: str | None = None
    用量3: Decimal | None = None
    単位コード3: str | None = None
    単位3: str | None = None
    薬剤コード4: str | None = None
    薬剤4: str | None = None
    用量4: Decimal | None = None
    単位コード4: str | None = None
    単位4: str | None = None
    薬剤コード5: str | None = None
    薬剤5: str | None = None
    用量5: Decimal | None = None
    単位コード5: str | None = None
    単位5: str | None = None
    薬剤コード6: str | None = None
    薬剤6: str | None = None
    用量6: Decimal | None = None
    単位コード6: str | None = None
    単位6: str | None = None
    薬剤コード7: str | None = None
    薬剤7: str | None = None
    用量7: Decimal | None = None
    単位コード7: str | None = None
    単位7: str | None = None
    薬剤コード8: str | None = None
    薬剤8: str | None = None
    用量8: Decimal | None = None
    単位コード8: str | None = None
    単位8: str | None = None
    薬剤コード9: str | None = None
    薬剤9: str | None = None
    用量9: Decimal | None = None
    単位コード9: str | None = None
    単位9: str | None = None
    薬剤コード10: str | None = None
    薬剤10: str | None = None
    用量10: Decimal | None = None
    単位コード10: str | None = None
    単位10: str | None = None


class 放射線治療実施(DwhBaseModel):
    """放射線治療実施内容（1治療計画(複数日にまたがる(クール))につき1レコード）."""

    ROW_ID: str = ""
    件数: int = 1
    シーケンスID: str = ""
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: Decimal = Decimal("0")
    キー8: Decimal = Decimal("0")
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    症例ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: Decimal = Decimal("0")
    治療開始時年齢: int | None = None
    治療開始時月齢: int | None = None
    治療開始時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_治療開始日_: date = Field(date(1000, 1, 1), alias="検索日(治療開始日)")
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    キャンセル日: date | None = None
    キャンセル時刻: time | None = None
    入外区分: str = ""
    保険分類: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    サブオーナー2の定義: str = ""
    サブオーナー2ID: str = ""
    サブオーナー2: str = ""
    サブオーナー2職種: str = ""
    検査種別名: str = ""
    治療SEQ: int | None = None
    基本情報KEY: str = ""
    治療計画No_: str | None = Field(None, alias="治療計画No.")
    実施日: date | None = None
    実施時刻: time | None = None
    部位コード: str | None = None
    部位名: str | None = None
    手技コード: str | None = None
    手技名1: str | None = None
    手技名2: str | None = None
    手技名3: str | None = None
    手技名4: str | None = None
    手技名5: str | None = None
    方向セット: str | None = None
    方向名1: str | None = None
    方向名2: str | None = None
    方向名3: str | None = None
    方向名4: str | None = None
    方向名5: str | None = None
    修飾セット: str | None = None
    修飾名1: str | None = None
    修飾名2: str | None = None
    修飾名3: str | None = None
    修飾名4: str | None = None
    修飾名5: str | None = None
    機能検査セット: str | None = None
    機能検査名1: str | None = None
    機能検査名2: str | None = None
    機能検査名3: str | None = None
    機能検査名4: str | None = None
    機能検査名5: str | None = None
    加算項目1: str | None = None
    加算項目2: str | None = None
    加算項目3: str | None = None
    加算項目4: str | None = None
    加算項目5: str | None = None
    加算項目6: str | None = None
    加算項目7: str | None = None
    加算項目8: str | None = None
    加算項目9: str | None = None
    加算項目10: str | None = None
    加算項目名1: str | None = None
    加算項目名2: str | None = None
    加算項目名3: str | None = None
    加算項目名4: str | None = None
    加算項目名5: str | None = None
    加算項目名6: str | None = None
    加算項目名7: str | None = None
    加算項目名8: str | None = None
    加算項目名9: str | None = None
    加算項目名10: str | None = None
    操作室コード: str | None = None
    操作室名: str | None = None
    装置_照射方法コード: str | None = Field(None, alias="装置・照射方法コード")
    装置_照射方法: str | None = Field(None, alias="装置・照射方法")
    撮影実施装置コード: str | None = None
    撮影実施装置: str | None = None
    治療装置コード: str | None = None
    治療装置名: str | None = None
    シミュレータ分類: str | None = None
    門数: int | None = None
    実施1回線量: Decimal | None = None
    治療_照準撮影区分: str | None = Field(None, alias="治療・照準撮影区分")
    撮影条件_LENG_: str | None = Field(None, alias="撮影条件(LENG)")
    撮影条件_KV_: str | None = Field(None, alias="撮影条件(KV)")
    撮影条件_mA_: str | None = Field(None, alias="撮影条件(mA)")
    撮影条件_sec_: str | None = Field(None, alias="撮影条件(sec)")
    フィルムの種類CD1: str | None = None
    フィルムの種類1: str | None = None
    フィルムの分割数1: int | None = None
    フィルム枚数1: int | None = None
    フィルムショット数1: int | None = None
    フィルムの種類CD2: str | None = None
    フィルムの種類2: str | None = None
    フィルムの分割数2: int | None = None
    フィルム枚数2: int | None = None
    フィルムショット数2: int | None = None
    フィルムの種類CD3: str | None = None
    フィルムの種類3: str | None = None
    フィルムの分割数3: int | None = None
    フィルム枚数3: int | None = None
    フィルムショット数3: int | None = None
    造影フラグ: str | None = None
    透視フラグ: str | None = None
    中止フラグ: str = ""
    実施フラグ: str = ""
    会計フラグ: str = ""
    操作者ID: str = ""
    操作者名: str = ""
    実施コメント: str = ""
    最終更新者ID: str = ""
    最終更新者名: str = ""
    検査医_ID: str = ""
    検査医: str = ""
    検査技師_ID: str = ""
    検査技師: str = ""
    プラン名: str | None = None
    ステータス: str | None = None


class 看護指示受け(DwhBaseModel):
    """看護師への指示の情報（1指示1レコード）."""

    ROW_ID: str = ""
    件数: int = 1
    シーケンスID: str = ""
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    指示開始時年齢: int | None = None
    指示開始時月齢: int | None = None
    指示開始時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_指示日_: date = Field(date(1000, 1, 1), alias="検索日(指示日)")
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    キャンセル日: date | None = None
    キャンセル時刻: time | None = None
    キャンセル種別: str = ""
    入外区分: str = ""
    保険分類: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    病室コード: str = ""
    病室: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    サブオーナー2の定義: str = ""
    サブオーナー2ID: str = ""
    サブオーナー2: str = ""
    サブオーナー2職種: str = ""
    部門連係ID: str = ""
    指示開始日: date | None = None
    指示開始時刻: time | None = None
    指示終了日: date | None = None
    指示終了時刻: time | None = None
    指示者ID: str = ""
    指示者: str = ""
    指示種別コード: str = ""
    指示種別: str = ""
    指示内容: str = ""
    指示詳細: str = ""
    指示受け状況: str = ""
    指示受け日: date | None = None
    指示受け時刻: time | None = None
    指示受け職種区分: str = ""
    指示受け職種: str = ""
    指示受け者ID: str = ""
    指示受け者: str = ""
    指示受け中止状況: str = ""
    指示受け中止者ID: str = ""
    指示受け中止者: str = ""
    検査目的コード: str = ""
    検査目的: str = ""
    指示の起票日: date | None = None
    指示の起票時刻: time | None = None
    与薬指示コメント: str = ""
    与薬指示番号: str = ""


class リハビリ(DwhBaseModel):
    """リハビリ実施内容（複数にまたがる1リハビリ計画につき1レコード）."""

    ROW_ID: str = ""
    件数: int = 1
    シーケンスID: str = ""
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    実施開始時年齢: int | None = None
    実施開始時月齢: int | None = None
    実施開始時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_実施開始日_: date = Field(date(1000, 1, 1), alias="検索日(実施開始日)")
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    キャンセル日: date | None = None
    キャンセル種別: str = ""
    キャンセル理由: str = ""
    入外区分: str = ""
    保険分類: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー2の定義: str = ""
    サブオーナー2ID: str = ""
    サブオーナー2: str = ""
    サブオーナー2職種: str = ""
    部門連係ID: str = ""
    実施開始日: date = date(1000, 1, 1)
    実施開始時刻: time | None = None
    実施終了日: date | None = None
    実施終了時刻: time | None = None
    手技コード: str = ""
    手技: str = ""
    単位数: int | None = None
    起算日: date | None = None
    療法種別: str = ""
    トータル実施時間_分_: int | None = Field(None, alias="トータル実施時間(分)")
    トータル実施回数: int | None = None
    実施場所コード: str = ""
    実施場所: str = ""
    疾病別分類コード: str = ""
    疾病別分類: str = ""
    主傷病名: str = ""
    実施状況: str = ""
    実施者ID: str = ""
    実施者: str = ""
    実施コメント: str = ""


class 輸血(DwhBaseModel):
    """輸血."""

    ROW_ID: str = ""
    件数: int = 1
    シーケンスID: str = ""
    トランザクション名: str = ""
    キー1: str = ""
    キー2: str = ""
    キー3: str = ""
    キー4: str = ""
    キー5: str = ""
    キー6: str = ""
    キー7: int = 0
    キー8: int = 0
    キー9: date = date(1000, 1, 1)
    キー10: time = time(0, 0, 0)
    ETL更新日: date = date(1000, 1, 1)
    ETL更新時刻: time = time(0, 0, 0)
    匿名ID: str = ""
    施設コード: str = ""
    施設名: str = ""
    患者ID: str = ""
    患者番号: float = 0.0
    輸血開始時年齢: int | None = None
    輸血開始時月齢: int | None = None
    輸血開始時日齢: int | None = None
    性別: str = ""
    検索日の定義: str = ""
    検索日_輸血開始日_: date = Field(date(1000, 1, 1), alias="検索日(輸血開始日)")
    検索時刻: time = time(0, 0, 0)
    入力日の定義: str = ""
    入力日: date | None = None
    入力時刻: time | None = None
    更新日の定義: str = ""
    更新日: date | None = None
    更新時刻: time | None = None
    キャンセル日の定義: str = ""
    キャンセル日: date | None = None
    キャンセル時刻: time | None = None
    キャンセル種別: str = ""
    入外区分: str = ""
    保険分類: str = ""
    診療科コード: str = ""
    診療科: str = ""
    病棟コード: str = ""
    病棟: str = ""
    オーナーの定義: str = ""
    オーナーID: str = ""
    オーナー: str = ""
    オーナー職種: str = ""
    サブオーナー1の定義: str = ""
    サブオーナー1ID: str = ""
    サブオーナー1: str = ""
    サブオーナー1職種: str = ""
    部門連係ID: str = ""
    輸血区分コード: str = ""
    輸血区分: str = ""
    緊急区分: str = ""
    疾患名: str = ""
    製剤グループコード: str = ""
    製剤グループ名: str = ""
    製剤グループ名_オーダー時_: str = Field("", alias="製剤グループ名(オーダー時)")
    投与方法: str = ""
    輸血予定開始日: date | None = None
    輸血予定開始時刻: time | None = None
    輸血予定終了日: date | None = None
    輸血予定終了時刻: time | None = None
    輸血実施開始日: date = date(1000, 1, 1)
    輸血実施開始時刻: time | None = None
    輸血実施終了日: date | None = None
    輸血実施終了時刻: time | None = None
    実施場所コード: str = ""
    実施場所: str = ""
    受取場所コード: str = ""
    受取場所: str = ""
    製剤種コード: str = ""
    製剤種名: str = ""
    ロットNo: str = ""
    輸血ABO: str = ""
    輸血RH: str = ""
    不規則性抗体の有無: str = ""
    他院輸血の有無: str = ""
    妊娠歴の有無: str = ""
    骨髄移植歴の有無: str = ""
    承諾書の有無: str = ""
    予定量: float | None = None
    予定量単位: str = ""
    実施量: float | None = None
    実施量単位: str = ""
    術式コード: str = ""
    術式: str = ""
    副作用コメントの有無: str = ""
    副作用コメント: str = ""
    依頼コメント: str = ""
    状況: str = ""
    副作用区分コード: str = ""
    副作用区分: str = ""
